export const categoriesData = [
  { id: 'soundcloud', key: 'soundcloud', image: '/example.png' },
  { id: 'fountain', key: 'fountain', image: '/example.png' },
  { id: 'handheld', key: 'handheld', image: '/example.png' },
  { id: 'spinning', key: 'spinning', image: '/example.png' },
  { id: 'poppop', key: 'poppop', image: '/example.png' },
  { id: 'dragonpili', key: 'dragonpili', image: '/example.png' },
  { id: 'fireworks', key: 'fireworks', image: '/example.png' },
  { id: 'firecrackers', key: 'firecrackers', image: '/example.png' },
  { id: 'skyline', key: 'skyline', image: '/example.png' },
];

export const mockProducts = [
  {
    id: 'pw-1',
    name: 'Thunder Crackers 100x',
    price: 15.99,
    originalPrice: 24.99,
    category: 'soundcloud',
    description: 'Extremely loud crackling strings of mini firecrackers.',
    image: '/example.png',
    stock: 125,
  },
  {
    id: 'pw-2',
    name: 'Volcano Eruption Fountain',
    price: 24.50,
    originalPrice: 35.00,
    category: 'fountain',
    description: 'A 2-minute dazzling ground display of shimmering blue and gold sparks accompanied by a whistling finale.',
    image: '/example.png',
    stock: 8,
  },
  {
    id: 'pw-3',
    name: 'Magic Wand Sparklers',
    price: 5.99,
    category: 'handheld',
    description: 'Long-lasting 20-inch sparklers emitting a stunning gold shower. Safe and perfect for parties or weddings.',
    image: '/example.png',
    stock: 450,
  },
  {
    id: 'pw-4',
    name: 'Ground Bloom Flower',
    price: 8.99,
    originalPrice: 12.50,
    category: 'spinning',
    description: 'Spins rapidly on the ground changing colors from green, red, and yellow.',
    image: '/example.png',
    stock: 12,
  },
  {
    id: 'pw-5',
    name: 'Super Snappers (Pop Pop)',
    price: 2.99,
    category: 'poppop',
    description: 'Classic noise makers! Throw them on the ground for a loud snap.',
    image: '/example.png',
    stock: 890,
  },
  {
    id: 'pw-6',
    name: 'Dragon Pearl Crackle',
    price: 12.99,
    originalPrice: 19.99,
    category: 'dragonpili',
    description: 'Small pearls that emit loud cracking sounds and bright sparks when ignited.',
    image: '/example.png',
    stock: 5,
  },
  {
    id: 'pw-7',
    name: 'Grand Finale Cake 500g',
    price: 89.99,
    originalPrice: 129.99,
    category: 'fireworks',
    description: 'The ultimate showstopper. 36 shots of gigantic brocade crowns with a rapid-fire crackling finish.',
    image: '/example.png',
    stock: 25,
  },
  {
    id: 'pw-8',
    name: 'Red Lantern Firecrackers',
    price: 19.99,
    category: 'firecrackers',
    description: 'Traditional red firecrackers strung together for festive celebrations.',
    image: '/example.png',
    stock: 150,
  },
  {
    id: 'pw-9',
    name: 'Neon Sky Rockets',
    price: 34.99,
    originalPrice: 49.99,
    category: 'skyline',
    description: 'A 6-pack of powerful rockets that streak into the air with a neon tail before bursting into colorful peonies.',
    image: '/example.png',
    stock: 0,
  }
];

export const getProducts = () => mockProducts;
export const getProductById = (id: string) => mockProducts.find(p => p.id === id);
