import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    products: 'Products',
    settings: 'Settings',
    customers: 'Customers',
    orders: 'Orders',
    total_customers: 'Total Customers',
    sellers: 'Sellers',
    guests: 'Guests',
    seller_setup: 'Seller Setup',
    business_setup: 'Business Setup',
    seller: 'Seller',
    guest: 'Guest',
    member: 'Member',
    discount: 'Discount',
    yes: 'Yes',
    no_label: 'No',
    customer_not_found: 'Customer not found.',
    back_to_customers: 'Back to Customers',
    back_to_customer: 'Back to Customer',
    back_to_list: 'Back to List',
    address: 'Address',
    no_address_provided: 'No address provided',
    registered_since: 'Registered Since',
    promote_to_seller: 'Promote to Seller',
    total_spent: 'Total Spent',
    order_history: 'Order History',
    latest_activity: 'Latest Activity',
    no_orders_yet: 'This customer hasn\'t placed any orders yet.',
    confirmation_dialog: 'Confirmation Dialog',
    promote_confirm_1: 'Are you sure you want to promote ',
    promote_confirm_2: ' to a Seller? They will gain access to exclusive supplier pricing.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    processing_dot: 'Processing...',
    retrieving_profile: 'Retrieving Profile...',
    syncing_profiles: 'Synchronizing Profiles...',
    no_customer_profiles_found: 'No matching customer profiles found.',
    total_products: 'Total Products',
    live_products: 'Live Products',
    total_orders: 'Total Orders',
    live_inventory: 'Live Inventory',
    active_products: 'Active Products',
    all_transactions: 'All Transactions',
    registered_customers: 'Total Customers',
    growth_members: 'Growth & Members',
    add_new_product: 'Add New Product',
    search_placeholder: 'Search products...',
    all_categories: 'All Categories',
    all_status: 'All Status',
    all_roles: 'All Roles',
    stock: 'Stock',
    price: 'Price',
    status: 'Status',
    delete_selected: 'Delete Selected',
    appearance: 'Visual Appearance',
    midnight_protocol: 'Midnight Protocol',
    daylight_clarity: 'Daylight Clarity',
    language_pref: 'Language Preference',
    english: 'English',
    chinese: 'Chinese',
    malay: 'Malay',
    save_settings: 'Save Settings',
    syncing: 'Synchronizing with database...',
    synced: 'Settings are synced across all sessions.',
    seller_levels: 'Seller Levels',
    sellers_list: 'Sellers List',
    add_level: 'Add Level',
    delete_level_confirm: 'Are you sure you want to delete this level? Sellers in this level will lose their benefits.',
    edit_level: 'Edit Level',
    new_seller_level: 'New Seller Level',
    level_name: 'Level Name',
    discount_percentage: 'Discount Percentage (%)',
    free_shipping_eligibility: 'Free Shipping Eligibility',
    save_level: 'Save Level',
    seller_setup_guide: 'Seller Setup Guide',
    silver_tier: 'Silver Tier (Level 1)',
    silver_tier_desc: 'Set up an entry-level tier for your new sellers. Typically, you can offer a ',
    five_percent_discount: '5% discount',
    on_all_products_without_fs: ' on all products without free shipping.',
    gold_tier: 'Gold Tier (Level 2)',
    gold_tier_desc: 'Create a mid-level tier to motivate your sellers. A good standard is a ',
    ten_percent_discount: '10% discount',
    on_all_products: ' on all products.',
    platinum_tier: 'Platinum Tier (Level 3)',
    platinum_tier_desc: 'Reward your top-performing sellers with the highest tier. Set it to a ',
    fifteen_percent_discount: '15% discount',
    and_enable: ' and enable ',
    free_shipping: 'Free Shipping',
    got_it: 'Got it',
    seller_name: 'Seller Name',
    performance: 'Performance',
    current_level: 'Current Level',
    actions: 'Actions',
    since: 'Since',
    no_level: 'No Level',
    suspended: 'Suspended',
    revoke_seller: 'Revoke Seller',
    no_sellers_found: 'No sellers found',
    system_overview: 'System Overview',
    system_preferences: 'System Preferences',
    system_preferences_desc: 'Manage your core business identity, contact information, and public links.',
    branding: 'Branding',
    business_name: 'Business Name',
    business_name_font: 'Business Name Font',
    preview: 'Preview',
    applied_to_header: 'Applied to header and footer business name',
    main_logo_image: 'Main Logo Image',
    change_logo: 'Change Logo',
    uploading: 'Uploading...',
    upload_logo: 'Upload Logo',
    transparent_logo: 'Transparent Logo',
    transparent_logo_tooltip: 'Used for watermarks on product images. Must be a PNG with a transparent background.',
    change_watermark: 'Change Watermark',
    upload_watermark: 'Upload Watermark',
    business_information: 'Business Information',
    phone_number: 'Phone Number',
    email_address: 'Email Address',
    whatsapp_number: 'WhatsApp Number',
    full_address: 'Full Address',
    social_media_links: 'Social Media Links',
    facebook_account: 'Facebook Account',
    instagram_handle: 'Instagram Handle',
    tiktok_handle: 'TikTok Handle',
    unsaved_changes: 'Unsaved changes',
    discard: 'Discard',
    confirm_settings: 'Confirm Settings',
    saving: 'Saving...',
    saved_successfully: 'Saved Successfully',
    saved_successfully_desc: 'Your business settings have been updated and are now live.',
    close: 'Close',
    revenue: 'Revenue',
    daily_revenue: 'Daily Revenue',
    top_selling_products: 'Top Selling Products',
    average_order_value: 'Average Order Value',
    total_sales: 'Total Sales',
    sales_metrics: 'Sales Metrics',
    last_30_days: 'Last 30 Days',
    units_sold: 'Units Sold',
    no_data: 'No data available',
    total_revenue: 'Total Revenue',
    completed_sales: 'Completed Sales',
    recent_transactions: 'Recent Transactions',
    market_split: 'Market Split',
    verified_sellers: 'Verified Sellers',
    regular_members: 'Regular Members',
    manage_customer_base: 'Manage Customer Base',
    view_inventory: 'View Inventory',
    members: 'Members',
    incoming: 'Pending',
    active_action: 'Active Action',
    fulfilled: 'Completed',
    cancelled: 'Cancelled',
    management: 'MANAGEMENT',
    view_more: 'View More',
    pending: 'Pending',
    in_process: 'In Process',
    completed: 'Completed',
    order_id: 'Order ID',
    total: 'Total',
    date: 'Date',
    click_to_manage: 'Click to manage',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    records: 'Records',
    page: 'Page',
    order_contents: 'Order Contents',
    customer_info: 'Customer Info',
    fulfillment_details: 'Fulfillment Details',
    order_control: 'Order Control',
    current_status: 'Current Status',
    save_changes: 'Save Changes',
    back_to_orders: 'Back to Orders',
    items: 'Items',
    subtotal: 'Subtotal',
    total_amount: 'Total Amount',
    processing: 'In Process',
    out_for_delivery: 'Delivering',
    name: 'Name',
    contact: 'Contact',
    shipping_address: 'Shipping Address',
    payment_method: 'Payment Method',
    fulfillment_mode: 'Fulfillment Mode',
    order_notes: 'Order Notes',
    order_placed: 'Order Placed',
    logout: 'Logout',
    no_recent_orders_found: 'No recent orders found.',
    scanning_order_records: 'Scanning Order Records...',
    no_order_records_found: 'No order records found.',
    order_record_not_found: 'Order Record Not Found.',
    loading_inventory: 'Loading Inventory...',
    no_products_found: 'No products match your filters.',
    order_id_tooltip: 'This ID represents the last 8 alphanumeric characters of the unique order identifier.',
    search_customers_placeholder: 'Search by name, phone or ID...',
    join_date: 'Join Date',
    phone: 'Phone',
    role: 'Role',
    customer: 'Customer',
    hold: 'Hold',
    deactive: 'Deactive',
    categories: 'Categories',
    add_new_category: 'Add New Category',
    export_csv: 'Export CSV',
    export_excel: 'Export Excel',
    export_pdf: 'Export PDF',
    out_of_stock: 'Out of Stock',
    low_stock: 'Low Stock',
    category_overview: 'Category Overview',
    upload_new_category: 'Upload New Category',
    upload_new_item: 'Upload New Item',
    visual_assets: 'Visual Assets',
    category_identity: 'Category Identity',
    product_identity: 'Product Identity',
    inventory_commerce: 'Inventory & Commerce',
    category_name_en: 'Category Name (English)',
    category_code: 'Category Code (URL Key)',
    product_name_en: 'Product Name (English)',
    chinese_translation: 'Chinese Translation (optional)',
    malay_translation: 'Malay Translation (optional)',
    item_description: 'Item Description',
    quantity_stock: 'Quantity Stock',
    original_price: 'Original Price (RM)',
    seller_price: 'Seller Price (RM)',
    sale_price: 'Sale Price (RM)',
    auto_gen: 'Auto-Gen',
    choose_category: '-- Choose Category --',
    upload_banner: 'Upload Category Banner Image',
    click_select_images: 'Click to Select Multiple Images',
    add_more: 'Add More',
    youtube_link: 'YouTube Video Link',
    open_youtube: 'Open YouTube',
    confirm_upload: 'Confirm Upload',
    category_created: 'Category Created Successfully!',
    done_return: 'Done & Return to Inventory',
    selected_banner: 'Selected Banner Asset',
    how_to_add_video: 'How to Add Video',
    yt_step_1: 'Click "Open YouTube" to visit youtube.com',
    yt_step_2: 'Find and open the video you want to display',
    yt_step_3: 'Copy the URL from the browser address bar',
    yt_step_4: 'Paste the copied link into this input box',
    col_no: 'No.',
    col_code: 'Code',
    col_name: 'Name',
    col_category: 'Category',
    col_stock: 'Stock',
    col_original_price: 'Original Price (RM)',
    col_promotion_price: 'Promotion Price (RM)',
    col_seller_price: 'Seller Price (RM)',
    col_status: 'Status',
    pdf_english_only: 'PDF exports are always in English. Chinese/Malay characters are not supported by the built-in PDF font.',
    loading: 'Loading...',
    fetching_product_details: 'Fetching Product Details...',
    product_not_found: 'Product not found',
    confirm_delete_product: 'Are you sure you want to delete this product?',
    failed_delete_product: 'Failed to delete product',
    back_to_inventory: 'Back to Inventory',
    view_live_store: 'View Live Store',
    edit_product: 'Edit Product',
    delete: 'Delete',
    stock_level: 'Stock Level',
    units: 'units',
    visibility: 'Visibility',
    pricing_structure: 'Pricing Structure',
    active_price: 'Active Price',
    you_save: 'You Save',
    base_price: 'Base Price',
    promo_price: 'Promo Price',
    last_updated: 'Last Updated',
    live_demonstration: 'Live Demonstration',
    product_demo: 'Product Demo',
    loading_product_data: 'Loading Product Data...',
    modify_product: 'Modify Product',
    listing_status: 'Listing Status',
    click_to_upload_images: 'Click to Upload New Images',
    cancel_changes: 'Cancel Changes',
    update_product_listing: 'Update Product Listing',
    please_upload_image: 'Please upload at least one image',
    please_select_category: 'Please select a category',
    product_code_required: 'Product code is required',
    failed_update_product: 'Failed to update product',
    failed_upload_images: 'Failed to upload images',
    please_input_name_auto_gen: 'Please input Product Name first to auto-generate code.',
    failed_auto_gen_code: 'Failed to auto-generate product code.',
    category: 'Category',
    product_code: 'Product Code',
    status_live: 'Live',
    status_hold: 'Hold',
    status_deactive: 'Deactive',
    err_image_required: 'Please upload at least one product image.',
    err_category_required: 'Please select a category.',
    err_code_required: 'Product code is required.',
    err_name_required: 'Product name is required.',
    err_stock_required: 'Stock quantity is required.',
    err_price_required: 'Original price is required.',
  },
  zh: {
    dashboard: '仪表盘',
    inventory: '库存管理',
    products: '产品',
    settings: '设置',
    customers: '客户',
    orders: '订单管理',
    total_customers: '客户总数',
    sellers: '卖家',
    guests: '游客',
    seller_setup: '卖家设置',
    business_setup: '商家设置',
    seller: '卖家',
    guest: '游客',
    member: '会员',
    discount: '折扣',
    yes: '是',
    no_label: '否',
    customer_not_found: '未找到客户。',
    back_to_customers: '返回客户列表',
    back_to_customer: '返回客户资料',
    back_to_list: '返回列表',
    address: '地址',
    no_address_provided: '未提供地址',
    registered_since: '注册日期',
    promote_to_seller: '升级为卖家',
    total_spent: '总消费',
    order_history: '历史订单',
    latest_activity: '最新动态',
    no_orders_yet: '该客户尚未下任何订单。',
    confirmation_dialog: '确认对话框',
    promote_confirm_1: '您确定要将 ',
    promote_confirm_2: ' 升级为卖家吗？他们将获得专属的供应商价格。',
    cancel: '取消',
    confirm: '确认',
    processing_dot: '处理中...',
    retrieving_profile: '获取个人资料...',
    syncing_profiles: '正在同步资料...',
    no_customer_profiles_found: '未找到匹配的客户资料。',
    total_products: '产品总数',
    live_products: '上架产品',
    total_orders: '订单总数',
    live_inventory: '实时库存',
    active_products: '活跃产品',
    all_transactions: '所有交易',
    registered_customers: '注册客户',
    growth_members: '增长与会员',
    add_new_product: '添加新产品',
    search_placeholder: '搜索产品...',
    all_categories: '所有类别',
    all_status: '所有状态',
    all_roles: '所有角色',
    stock: '库存',
    price: '价格',
    status: '状态',
    delete_selected: '删除选中项',
    appearance: '视觉外观',
    midnight_protocol: '午夜模式',
    daylight_clarity: '白昼模式',
    language_pref: '语言偏好',
    english: '英文',
    chinese: '中文',
    malay: '马来文',
    save_settings: '保存设置',
    syncing: '正在同步到数据库...',
    synced: '设置已在所有会话中同步。',
    seller_levels: '卖家等级',
    sellers_list: '卖家列表',
    add_level: '添加等级',
    delete_level_confirm: '确定要删除此等级吗？此等级下的卖家将失去其福利。',
    edit_level: '编辑等级',
    new_seller_level: '新建卖家等级',
    level_name: '等级名称',
    discount_percentage: '折扣百分比 (%)',
    free_shipping_eligibility: '免运费资格',
    save_level: '保存等级',
    seller_setup_guide: '卖家设置指南',
    silver_tier: '白银等级 (1 级)',
    silver_tier_desc: '为您的新卖家设置入门等级。通常，您可以提供 ',
    five_percent_discount: '5% 的折扣',
    on_all_products_without_fs: '，不含免运费。',
    gold_tier: '黄金等级 (2 级)',
    gold_tier_desc: '创建一个中等等级来激励您的卖家。一个很好的标准是 ',
    ten_percent_discount: '10% 的折扣',
    on_all_products: '。',
    platinum_tier: '白金等级 (3 级)',
    platinum_tier_desc: '用最高等级奖励您表现最好的卖家。将其设置为 ',
    fifteen_percent_discount: '15% 的折扣',
    and_enable: ' 并启用',
    free_shipping: '免运费',
    got_it: '知道了',
    seller_name: '卖家名称',
    performance: '表现',
    current_level: '当前等级',
    actions: '操作',
    since: '自',
    no_level: '无等级',
    suspended: '已暂停',
    revoke_seller: '撤销卖家身份',
    no_sellers_found: '未找到卖家',
    system_overview: '系统概览',
    system_preferences: '系统偏好设置',
    system_preferences_desc: '管理您的核心业务标识、联系信息和公共链接。',
    branding: '品牌建设',
    business_name: '商家名称',
    business_name_font: '商家名称字体',
    preview: '预览',
    applied_to_header: '应用于页眉和页脚的商家名称',
    main_logo_image: '主标志图片',
    change_logo: '更改标志',
    uploading: '上传中...',
    upload_logo: '上传标志',
    transparent_logo: '透明标志',
    transparent_logo_tooltip: '用于产品图片上的水印。必须是透明背景的 PNG 格式。',
    change_watermark: '更改水印',
    upload_watermark: '上传水印',
    business_information: '商家信息',
    phone_number: '电话号码',
    email_address: '电子邮件地址',
    whatsapp_number: 'WhatsApp 号码',
    full_address: '完整地址',
    social_media_links: '社交媒体链接',
    facebook_account: 'Facebook 账号',
    instagram_handle: 'Instagram 账号',
    tiktok_handle: 'TikTok 账号',
    unsaved_changes: '未保存的更改',
    discard: '放弃',
    confirm_settings: '确认设置',
    saving: '保存中...',
    saved_successfully: '保存成功',
    saved_successfully_desc: '您的商家设置已更新并生效。',
    close: '关闭',
    revenue: '收入',
    daily_revenue: '每日收入',
    top_selling_products: '畅销产品',
    average_order_value: '平均订单价值',
    total_sales: '总销售额',
    sales_metrics: '销售指标',
    last_30_days: '过去 30 天',
    units_sold: '售出数量',
    no_data: '暂无数据',
    total_revenue: '总收入',
    completed_sales: '已完成销售',
    recent_transactions: '最近交易',
    market_split: '市场分布',
    verified_sellers: '认证卖家',
    regular_members: '普通会员',
    manage_customer_base: '管理客户群',
    view_inventory: '查看库存',
    members: '会员',
    incoming: '待处理',
    active_action: '正在处理',
    fulfilled: '已完成',
    cancelled: '已取消',
    management: '管理',
    view_more: '查看更多',
    pending: '待处理',
    in_process: '处理中',
    completed: '已完成',
    order_id: '订单编号',
    total: '总额',
    date: '日期',
    click_to_manage: '点击管理',
    showing: '显示',
    to: '至',
    of: '共',
    records: '条记录',
    page: '第',
    order_contents: '订单内容',
    customer_info: '客户信息',
    fulfillment_details: '履行详情',
    order_control: '订单控制',
    current_status: '当前状态',
    save_changes: '保存修改',
    back_to_orders: '返回订单列表',
    items: '件商品',
    subtotal: '小计',
    total_amount: '总金额',
    processing: '正在处理',
    out_for_delivery: '正在派送',
    name: '名称',
    contact: '联系方式',
    shipping_address: '收货地址',
    payment_method: '支付方式',
    fulfillment_mode: '履行模式',
    order_notes: '订单备注',
    order_placed: '下单时间',
    logout: '退出登录',
    no_recent_orders_found: '未找到近期订单。',
    scanning_order_records: '正在扫描订单记录...',
    no_order_records_found: '未找到订单记录。',
    order_record_not_found: '找不到订单记录。',
    loading_inventory: '正在加载库存...',
    no_products_found: '没有找到符合条件的产品。',
    order_id_tooltip: '此编号代表唯一订单标识符的最后 8 位字母数字字符。',
    search_customers_placeholder: '搜索名称、电话或ID...',
    join_date: '加入日期',
    phone: '电话',
    role: '角色',
    customer: '客户',
    hold: '暂停',
    deactive: '已下架',
    categories: '分类',
    add_new_category: '添加新分类',
    export_csv: '导出 CSV',
    export_excel: '导出 Excel',
    export_pdf: '导出 PDF',
    out_of_stock: '缺货',
    low_stock: '库存不足',
    category_overview: '分类概览',
    upload_new_category: '上传新分类',
    upload_new_item: '上传新产品',
    visual_assets: '视觉资源',
    category_identity: '分类信息',
    product_identity: '产品信息',
    inventory_commerce: '库存与商业',
    category_name_en: '分类名称（英文）',
    category_code: '分类代码',
    product_name_en: '产品名称（英文）',
    chinese_translation: '中文翻译（可选）',
    malay_translation: '马来文翻译（可选）',
    item_description: '产品描述',
    quantity_stock: '库存数量',
    original_price: '原价 (RM)',
    seller_price: '卖家价 (RM)',
    sale_price: '促销价 (RM)',
    auto_gen: '自动生成',
    choose_category: '-- 选择分类 --',
    upload_banner: '上传分类封面图片',
    click_select_images: '点击选择多张图片',
    add_more: '继续添加',
    youtube_link: 'YouTube 视频链接',
    open_youtube: '打开 YouTube',
    confirm_upload: '确认上传',
    category_created: '分类创建成功！',
    done_return: '完成并返回库存',
    selected_banner: '已选封面图片',
    how_to_add_video: '如何添加视频',
    yt_step_1: '点击「打开 YouTube」访问 youtube.com',
    yt_step_2: '找到并打开您要显示的视频',
    yt_step_3: '从浏览器地址栏复制链接',
    yt_step_4: '将复制的链接粘贴到输入框中',
    col_no: '编号',
    col_code: '代码',
    col_name: '名称',
    col_category: '分类',
    col_stock: '库存',
    col_original_price: '原价 (RM)',
    col_promotion_price: '促销价 (RM)',
    col_seller_price: '卖家价 (RM)',
    col_status: '状态',
    pdf_english_only: 'PDF 导出时始终使用英文。PDF 内置字体不支持中文字符，如需中文表格请使用 Excel 导出。',
    loading: '加载中...',
    fetching_product_details: '获取产品详情中...',
    product_not_found: '未找到该产品',
    confirm_delete_product: '您确定要删除这个产品吗？',
    failed_delete_product: '删除产品失败',
    back_to_inventory: '返回库存列表',
    view_live_store: '查看线上店铺',
    edit_product: '编辑产品',
    delete: '删除',
    stock_level: '库存水平',
    units: '件',
    visibility: '可见性',
    pricing_structure: '价格结构',
    active_price: '当前价格',
    you_save: '您节省',
    base_price: '底价',
    promo_price: '促销价',
    last_updated: '最后更新',
    live_demonstration: '实物演示',
    product_demo: '产品演示',
    loading_product_data: '加载产品数据中...',
    modify_product: '修改产品',
    listing_status: '产品状态',
    click_to_upload_images: '点击上传新图片',
    cancel_changes: '取消修改',
    update_product_listing: '更新产品列表',
    please_upload_image: '请上传至少一张图片',
    please_select_category: '请选择分类',
    product_code_required: '产品代码是必填的',
    failed_update_product: '更新产品失败',
    failed_upload_images: '上传图片失败',
    please_input_name_auto_gen: '请先输入产品名称以自动生成代码。',
    failed_auto_gen_code: '自动生成产品代码失败。',
    category: '分类',
    product_code: '产品代码',
    status_live: '上架',
    status_hold: '暂停',
    status_deactive: '下架',
    err_image_required: '请上传至少一张产品图片。',
    err_category_required: '请选择分类。',
    err_code_required: '产品代码为必填项。',
    err_name_required: '产品名称为必填项。',
    err_stock_required: '库存数量为必填项。',
    err_price_required: '原价为必填项。',
  },
  ms: {
    dashboard: 'Papan Pemuka',
    inventory: 'Inventori',
    products: 'Produk',
    settings: 'Tetapan',
    customers: 'Pelanggan',
    orders: 'Pesanan',
    total_customers: 'Jumlah Pelanggan',
    sellers: 'Penjual',
    guests: 'Tetamu',
    seller_setup: 'Persediaan Penjual',
    business_setup: 'Persediaan Perniagaan',
    seller: 'Penjual',
    guest: 'Tetamu',
    member: 'Ahli',
    discount: 'Diskaun',
    yes: 'Ya',
    no_label: 'Tidak',
    customer_not_found: 'Pelanggan tidak dijumpai.',
    back_to_customers: 'Kembali ke Pelanggan',
    back_to_customer: 'Kembali ke Pelanggan',
    back_to_list: 'Kembali ke Senarai',
    address: 'Alamat',
    no_address_provided: 'Tiada alamat diberikan',
    registered_since: 'Mendaftar Sejak',
    promote_to_seller: 'Naik taraf kepada Penjual',
    total_spent: 'Jumlah Perbelanjaan',
    order_history: 'Sejarah Pesanan',
    latest_activity: 'Aktiviti Terkini',
    no_orders_yet: 'Pelanggan ini belum membuat sebarang pesanan lagi.',
    confirmation_dialog: 'Dialog Pengesahan',
    promote_confirm_1: 'Adakah anda pasti mahu menaik taraf ',
    promote_confirm_2: ' kepada Penjual? Mereka akan mendapat akses kepada harga pembekal eksklusif.',
    cancel: 'Batal',
    confirm: 'Sahkan',
    processing_dot: 'Memproses...',
    retrieving_profile: 'Mendapatkan Profil...',
    syncing_profiles: 'Menyelaraskan Profil...',
    no_customer_profiles_found: 'Tiada profil pelanggan yang sepadan ditemui.',
    total_products: 'Jumlah Produk',
    live_products: 'Produk Aktif',
    total_orders: 'Jumlah Pesanan',
    live_inventory: 'Inventori Langsung',
    active_products: 'Produk Aktif',
    all_transactions: 'Semua Transaksi',
    registered_customers: 'Pelanggan Berdaftar',
    growth_members: 'Pertumbuhan & Ahli',
    add_new_product: 'Tambah Produk Baru',
    search_placeholder: 'Cari produk...',
    all_categories: 'Semua Kategori',
    all_status: 'Semua Status',
    all_roles: 'Semua Peranan',
    stock: 'Stok',
    price: 'Harga',
    status: 'Status',
    delete_selected: 'Padam Terpilih',
    appearance: 'Penampilan Visual',
    midnight_protocol: 'Protokol Tengah Malam',
    daylight_clarity: 'Kejelasan Siang',
    language_pref: 'Pilihan Bahasa',
    english: 'Inggeris',
    chinese: 'Cina',
    malay: 'Melayu',
    save_settings: 'Simpan Tetapan',
    syncing: 'Menyelaras dengan pangkalan data...',
    synced: 'Tetapan diselaraskan merentas semua sesi.',
    seller_levels: 'Tahap Penjual',
    sellers_list: 'Senarai Penjual',
    add_level: 'Tambah Tahap',
    delete_level_confirm: 'Adakah anda pasti mahu memadam tahap ini? Penjual dalam tahap ini akan kehilangan faedah mereka.',
    edit_level: 'Edit Tahap',
    new_seller_level: 'Tahap Penjual Baru',
    level_name: 'Nama Tahap',
    discount_percentage: 'Peratusan Diskaun (%)',
    free_shipping_eligibility: 'Kelayakan Penghantaran Percuma',
    save_level: 'Simpan Tahap',
    seller_setup_guide: 'Panduan Persediaan Penjual',
    silver_tier: 'Tahap Perak (Tahap 1)',
    silver_tier_desc: 'Sediakan tahap permulaan untuk penjual baru anda. Biasanya, anda boleh menawarkan ',
    five_percent_discount: 'diskaun 5%',
    on_all_products_without_fs: ' pada semua produk tanpa penghantaran percuma.',
    gold_tier: 'Tahap Emas (Tahap 2)',
    gold_tier_desc: 'Buat tahap pertengahan untuk memotivasikan penjual anda. Standard yang baik adalah ',
    ten_percent_discount: 'diskaun 10%',
    on_all_products: ' pada semua produk.',
    platinum_tier: 'Tahap Platinum (Tahap 3)',
    platinum_tier_desc: 'Ganjarkan penjual terbaik anda dengan tahap tertinggi. Tetapkannya kepada ',
    fifteen_percent_discount: 'diskaun 15%',
    and_enable: ' dan dayakan ',
    free_shipping: 'Penghantaran Percuma',
    got_it: 'Faham',
    seller_name: 'Nama Penjual',
    performance: 'Prestasi',
    current_level: 'Tahap Semasa',
    actions: 'Tindakan',
    since: 'Sejak',
    no_level: 'Tiada Tahap',
    suspended: 'Digantung',
    revoke_seller: 'Tarik Balik Penjual',
    no_sellers_found: 'Tiada penjual dijumpai',
    system_overview: 'Gambaran Keseluruhan Sistem',
    system_preferences: 'Keutamaan Sistem',
    system_preferences_desc: 'Urus identiti teras perniagaan, maklumat hubungan dan pautan awam anda.',
    branding: 'Penjenamaan',
    business_name: 'Nama Perniagaan',
    business_name_font: 'Fon Nama Perniagaan',
    preview: 'Pratonton',
    applied_to_header: 'Digunakan pada nama perniagaan pengepala dan pengaki',
    main_logo_image: 'Imej Logo Utama',
    change_logo: 'Tukar Logo',
    uploading: 'Memuat naik...',
    upload_logo: 'Muat Naik Logo',
    transparent_logo: 'Logo Telus',
    transparent_logo_tooltip: 'Digunakan untuk tera air pada imej produk. Mesti berformat PNG dengan latar belakang telus.',
    change_watermark: 'Tukar Tera Air',
    upload_watermark: 'Muat Naik Tera Air',
    business_information: 'Maklumat Perniagaan',
    phone_number: 'Nombor Telefon',
    email_address: 'Alamat E-mel',
    whatsapp_number: 'Nombor WhatsApp',
    full_address: 'Alamat Penuh',
    social_media_links: 'Pautan Media Sosial',
    facebook_account: 'Akaun Facebook',
    instagram_handle: 'Akaun Instagram',
    tiktok_handle: 'Akaun TikTok',
    unsaved_changes: 'Perubahan yang belum disimpan',
    discard: 'Batal',
    confirm_settings: 'Sahkan Tetapan',
    saving: 'Menyimpan...',
    saved_successfully: 'Berjaya Disimpan',
    saved_successfully_desc: 'Tetapan perniagaan anda telah dikemas kini dan kini aktif.',
    close: 'Tutup',
    revenue: 'Hasil',
    daily_revenue: 'Hasil Harian',
    top_selling_products: 'Produk Terlaris',
    average_order_value: 'Purata Nilai Pesanan',
    total_sales: 'Jumlah Jualan',
    sales_metrics: 'Metrik Jualan',
    last_30_days: '30 Hari Terakhir',
    units_sold: 'Unit Terjual',
    no_data: 'Tiada data',
    total_revenue: 'Jumlah Hasil',
    completed_sales: 'Jualan Selesai',
    recent_transactions: 'Transaksi Terkini',
    market_split: 'Pecahan Pasaran',
    verified_sellers: 'Penjual Sah',
    regular_members: 'Ahli Biasa',
    manage_customer_base: 'Urus Pangkalan Pelanggan',
    view_inventory: 'Lihat Inventori',
    members: 'Ahli',
    incoming: 'Menunggu',
    active_action: 'Tindakan Aktif',
    fulfilled: 'Selesai',
    cancelled: 'Dibatalkan',
    management: 'PENGURUSAN',
    view_more: 'Lihat Lagi',
    pending: 'Menunggu',
    in_process: 'Sedang Diproses',
    completed: 'Selesai',
    order_id: 'ID Pesanan',
    total: 'Jumlah',
    date: 'Tarikh',
    click_to_manage: 'Klik untuk urus',
    showing: 'Menunjukkan',
    to: 'hingga',
    of: 'daripada',
    records: 'Rekod',
    page: 'Halaman',
    order_contents: 'Kandungan Pesanan',
    customer_info: 'Maklumat Pelanggan',
    fulfillment_details: 'Butiran Pemenuhan',
    order_control: 'Kawalan Pesanan',
    current_status: 'Status Semasa',
    save_changes: 'Simpan Perubahan',
    back_to_orders: 'Kembali ke Pesanan',
    items: 'Item',
    subtotal: 'Sub-jumlah',
    total_amount: 'Jumlah Besar',
    processing: 'Dalam Proses',
    out_for_delivery: 'Dalam Penghantaran',
    name: 'Nama',
    contact: 'Hubungi',
    shipping_address: 'Alamat Penghantaran',
    payment_method: 'Kaedah Pembayaran',
    fulfillment_mode: 'Mod Pemenuhan',
    order_notes: 'Nota Pesanan',
    order_placed: 'Pesanan Dibuat',
    logout: 'Log Keluar',
    no_recent_orders_found: 'Tiada pesanan terbaru ditemui.',
    scanning_order_records: 'Sedang Mengimbas Rekod Pesanan...',
    no_order_records_found: 'Tiada rekod pesanan ditemui.',
    order_record_not_found: 'Rekod Pesanan Tidak Ditemui.',
    loading_inventory: 'Sedang Memuatkan Inventori...',
    no_products_found: 'Tiada produk yang sepadan ditemui.',
    order_id_tooltip: 'ID ini mewakili 8 aksara alfanumerik terakhir daripada pengecam pesanan unik.',
    search_customers_placeholder: 'Cari mengikut nama, telefon atau ID...',
    join_date: 'Tarikh Sertai',
    phone: 'Telefon',
    role: 'Peranan',
    customer: 'Pelanggan',
    hold: 'Tahan',
    deactive: 'Tidak Aktif',
    categories: 'Kategori',
    add_new_category: 'Tambah Kategori Baru',
    export_csv: 'Eksport CSV',
    export_excel: 'Eksport Excel',
    export_pdf: 'Eksport PDF',
    out_of_stock: 'Kehabisan Stok',
    low_stock: 'Stok Rendah',
    category_overview: 'Gambaran Keseluruhan Kategori',
    upload_new_category: 'Muat Naik Kategori Baru',
    upload_new_item: 'Muat Naik Produk Baru',
    visual_assets: 'Aset Visual',
    category_identity: 'Identiti Kategori',
    product_identity: 'Identiti Produk',
    inventory_commerce: 'Inventori & Perdagangan',
    category_name_en: 'Nama Kategori (Inggeris)',
    category_code: 'Kod Kategori',
    product_name_en: 'Nama Produk (Inggeris)',
    chinese_translation: 'Terjemahan Cina (pilihan)',
    malay_translation: 'Terjemahan Melayu (pilihan)',
    item_description: 'Penerangan Produk',
    quantity_stock: 'Kuantiti Stok',
    original_price: 'Harga Asal (RM)',
    seller_price: 'Harga Penjual (RM)',
    sale_price: 'Harga Promosi (RM)',
    auto_gen: 'Jana Auto',
    choose_category: '-- Pilih Kategori --',
    upload_banner: 'Muat Naik Imej Banner Kategori',
    click_select_images: 'Klik untuk Pilih Beberapa Gambar',
    add_more: 'Tambah Lagi',
    youtube_link: 'Pautan Video YouTube',
    open_youtube: 'Buka YouTube',
    confirm_upload: 'Sahkan Muat Naik',
    category_created: 'Kategori Berjaya Dicipta!',
    done_return: 'Selesai & Kembali ke Inventori',
    selected_banner: 'Aset Banner Dipilih',
    how_to_add_video: 'Cara Tambah Video',
    yt_step_1: 'Klik "Buka YouTube" untuk lawati youtube.com',
    yt_step_2: 'Cari dan buka video yang ingin dipaparkan',
    yt_step_3: 'Salin URL dari bar alamat pelayar',
    yt_step_4: 'Tampalkan pautan yang disalin ke dalam kotak input ini',
    col_no: 'No.',
    col_code: 'Kod',
    col_name: 'Nama',
    col_category: 'Kategori',
    col_stock: 'Stok',
    col_original_price: 'Harga Asal (RM)',
    col_promotion_price: 'Harga Promosi (RM)',
    col_seller_price: 'Harga Penjual (RM)',
    col_status: 'Status',
    pdf_english_only: 'Eksport PDF sentiasa dalam Bahasa Inggeris. Aksara Cina/Melayu tidak disokong oleh fon PDF lalai. Sila gunakan Excel untuk jadual berbilang bahasa.',
    loading: 'Memuatkan...',
    fetching_product_details: 'Mendapatkan Butiran Produk...',
    product_not_found: 'Produk tidak ditemui',
    confirm_delete_product: 'Adakah anda pasti mahu memadam produk ini?',
    failed_delete_product: 'Gagal memadam produk',
    back_to_inventory: 'Kembali ke Inventori',
    view_live_store: 'Lihat Kedai Langsung',
    edit_product: 'Edit Produk',
    delete: 'Padam',
    stock_level: 'Tahap Stok',
    units: 'unit',
    visibility: 'Keterlihatan',
    pricing_structure: 'Struktur Harga',
    active_price: 'Harga Aktif',
    you_save: 'Anda Jimat',
    base_price: 'Harga Asas',
    promo_price: 'Harga Promo',
    last_updated: 'Terakhir Dikemas Kini',
    live_demonstration: 'Demonstrasi Langsung',
    product_demo: 'Demo Produk',
    loading_product_data: 'Memuatkan Data Produk...',
    modify_product: 'Ubah Suai Produk',
    listing_status: 'Status Produk',
    click_to_upload_images: 'Klik untuk Muat Naik Imej Baru',
    cancel_changes: 'Batal Perubahan',
    update_product_listing: 'Kemas Kini Senarai Produk',
    please_upload_image: 'Sila muat naik sekurang-kurangnya satu imej',
    please_select_category: 'Sila pilih kategori',
    product_code_required: 'Kod produk diperlukan',
    failed_update_product: 'Gagal mengemas kini produk',
    failed_upload_images: 'Gagal memuat naik imej',
    please_input_name_auto_gen: 'Sila masukkan Nama Produk terlebih dahulu untuk menjana kod secara automatik.',
    failed_auto_gen_code: 'Gagal menjana kod produk secara automatik.',
    category: 'Kategori',
    product_code: 'Kod Produk',
    status_live: 'Aktif',
    status_hold: 'Tahan',
    status_deactive: 'Nyahaktif',
    err_image_required: 'Sila muat naik sekurang-kurangnya satu gambar produk.',
    err_category_required: 'Sila pilih kategori.',
    err_code_required: 'Kod produk diperlukan.',
    err_name_required: 'Nama produk diperlukan.',
    err_stock_required: 'Kuantiti stok diperlukan.',
    err_price_required: 'Harga asal diperlukan.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // 1. Instantly retrieve saved preference from memory on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('admin_selected_language');
      if (savedLang && ['en', 'zh', 'ms'].includes(savedLang)) {
        setLanguageState(savedLang as Language);
      }
    }
  }, []);

  // 2. Custom setLanguage wrapper to update state & persist to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('admin_selected_language', lang);
    }
  };

  // 3. Keep database preferences in sync if logged in as admin
  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const res = await fetch('/api/admin/profile');
        if (res.ok) {
          const data = await res.json();
          if (data.language) {
            setLanguage(data.language as Language);
          }
        }
      } catch (err) {}
    };
    fetchSettings();
  }, []);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
