import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {

    placed_on: 'Placed on',
    self_collect: 'Self Collect',
    delivery: 'Delivery',
    edit_shipping_address: 'Edit Shipping Address',
    resend_confirmation: 'Resend Confirmation',
    save_changes: 'Save changes',
    cash_on_delivery: 'Cash On Delivery',
    bank_transfer: 'Bank Transfer',
    qr_code: 'DuitNow QR Code',
    generate_receipt: 'Generate Receipt',
    status_tutorial_desc: 'Order statuses follow a strict sequential flow to ensure accurate tracking. You can only progress an order forward step-by-step.',
    type_message_placeholder: 'Type a message to the customer...',
    email: 'Email',
    whatsapp: 'WhatsApp',
    sending: 'Sending...',
    cannot: 'cannot',
    qm_processing: 'Processing',
    qm_processing_text: 'We have received your order and are currently processing it.',
    qm_out_for_delivery: 'Out for Delivery',
    qm_out_for_delivery_text: 'Great news! Your order is out for delivery.',
    qm_ready_for_pickup: 'Ready for Pickup',
    qm_ready_for_pickup_text: 'Your order is packed and ready for pickup!',
    qm_delayed: 'Delayed',
    qm_delayed_text: 'There is a slight delay with your order, we will keep you updated.',
    more_actions: 'More actions',
    edit_shipping_address: 'Edit Shipping Address',
    refund_cancel_order: 'Refund / Cancel Order',
    order_status_title: 'Order Status',
    payment_method_title: 'Payment Method',
    fulfillment_method_title: 'Fulfillment Method',
    customer_info: 'Customer Information',
    shipping_address: 'Shipping Address',
    payment_fulfillment: 'Payment & Fulfillment',
    view_receipt: 'View receipt',
    payment_receipt: 'Payment Receipt',
    order_contents: 'Order Contents',
    subtotal: 'Subtotal',
    current: 'Current',
    update_status_desc: 'Update the status to keep your customer informed.',
    communication: 'Communication',
    quick_messages: 'Quick Messages',
    whatsapp: 'WhatsApp',
    status_tutorial_title: 'Status Flow Tutorial',
    status_tutorial_subtitle: 'Understanding Order Progression',
    status_tutorial_desc: 'Order statuses follow a strict sequential flow to ensure accurate tracking. You can only progress an order forward step-by-step.',
    status_pending_desc: 'Order is received. Awaiting admin review or payment confirmation.',
    status_in_process_desc: 'Order is confirmed. Items are being packed and prepared.',
    status_delivering_desc: 'Package is out for delivery or ready for customer pickup.',
    status_completed_desc: 'Successfully fulfilled. No further actions can be taken.',
    status_cancelled_desc: 'Order was cancelled before fulfillment. Stock may be returned.',
    important_note: 'Important Note:',
    cannot: 'cannot',
    be_cancelled_completed: ' be cancelled once they reach the Completed state.',
    success_exclaim: 'Success!',
    continue_btn: 'Continue',
    update_address_desc: 'Update the delivery address for this order.',
    cancel_order_q: 'Cancel Order?',
    cancel_order_confirm: 'Are you sure you want to cancel this order?',
    cancel_order_desc1: 'The product stock will be automatically restored to your inventory.',
    cancel_order_desc2: 'This action cannot be undone.',
    back: 'Back',
    total_orders_today: 'Total Orders Today',
    total_all_orders: 'Total All Orders',
    order_completed_kpi: 'Order Completed',
    in_process_order: 'In-Process Order',
    pending_order: 'Pending Order',
    cancelled_order_kpi: 'Cancelled Order',
    delivering_order: 'Delivering Order',
    bank_transfer: 'Bank Transfer',
    qr_code: 'DuitNow QR Code',
    cash_on_delivery: 'Cash On Delivery',
    payment_methods: 'Payment Methods',
    payment_methods_desc: 'Breakdown of all order payment types',
    no_payment_data: 'No payment data',
    filter_by_month: 'Filter by Month',
    clear: 'Clear',
    apply: 'Apply',
    order_id: 'Order ID',
    customer_name: 'Customer Name',
    phone_number: 'Phone Number',
    items: 'Items',
    total_amount: 'Total Amount',
    loading_orders: 'Loading Orders...',
    no_order_records: 'No order records found.',
    showing: 'Showing',
    records: 'records',
    all_filter: 'All',
    pending_filter: 'Pending',
    in_process_filter: 'In-Process',
    delivering_filter: 'Delivering',
    completed_filter: 'Completed',
    cancelled_filter: 'Cancelled',
    search_orders_placeholder: 'Search order ID, customer name...',
    total: 'Total',
    orders_list: 'Orders List',
    edit_product_desc: 'Modify the product details, pricing, and status.',
    fill_required_fields_err: 'Please fill in all required fields marked in red.',
    product_info: 'Product Information',
    product_code: 'Product Code',
    auto_gen: 'Auto-Gen',
    single_pricing_stock: 'Single Item Pricing & Stock',
    total_stock: 'Total Stock',
    normal_price: 'Normal Price ($)',
    agent_price: 'Agent Price ($)',
    promo_price: 'Promo Price ($)',
    per_box_pricing: 'Per Box Pricing (Optional)',
    items_per_box: 'Items Per Box',
    box_price: 'Box Price ($)',
    box_agent_price: 'Box Agent Price ($)',
    box_promo_price: 'Box Promo Price ($)',
    bundle_pricing: 'Bundle Set Pricing (Optional)',
    items_per_bundle: 'Items Per Bundle',
    bundle_price: 'Bundle Price ($)',
    bundle_agent_price: 'Bundle Agent Price ($)',
    bundle_promo_price: 'Bundle Promo Price ($)',
    visual_assets: 'Visual Assets',
    click_to_upload_images: 'Click to upload images',
    image_size_hint: 'PNG, JPG up to 10MB',
    youtube_link_optional: 'Youtube Video Link (optional)',
    open_youtube: 'Open YouTube',
    how_to_add_video: 'How to Add Video',
    youtube_step1: 'Click "Open YouTube" to visit youtube.com',
    youtube_step2: 'Find and open the video you want to display',
    youtube_step3: 'Copy the URL from the browser address bar',
    youtube_step4: 'Paste the copied link into this input box',
    cancel: 'Cancel',
    save_changes: 'Save Changes',
    import_completed: 'Import Completed',
    bulk_upload_processed: 'Your bulk upload has been processed.',
    success_label: 'Success',
    failed_label: 'Failed',
    error_details: 'Error Details',
    return_to_inventory: 'Return to Inventory',
    importing_products: 'Importing Products',
    importing_products_desc: 'Please wait while we upload your images and save the product data to the database. This may take a few moments.',
    upload_package: 'Upload Package',
    upload_package_desc: 'Package must contain the filled Excel template and all associated product images.',
    dont_have_template: 'Don\'t have the official template yet?',
    preview_validation_title: 'Preview & Validation',
    row: 'Row',
    image: 'Image',
    missing: 'Missing',
    reupload: 'Re-upload',
    upload_zip_msg: 'Please upload a ZIP file containing the excel and images.',
    read_zip_err: 'Failed to read ZIP file',
    no_excel_err: 'No Excel file (.xlsx) found in the ZIP package.',
    empty_excel_err: 'The Excel file is empty.',
    process_products_err: 'Failed to process products',
    no_valid_products: 'No valid products found to import.',
    products_text: 'Products',
    found: 'Found',
    issues: 'Issues',
    importing: 'Importing',
    description_en: 'Description (English)',
    eg_thunder_clap: 'e.g. Thunder Clap',
    eg_thunder_clap_zh: 'e.g. 雷霆万钧',
    eg_tc00001: 'e.g. TC00001',
    product_details_ph: 'Product details...',
    product_details_zh_ph: '产品详情...',
    choose_category: 'Choose Category',
    upload_new_product_desc: 'Add a new product to your inventory and set its pricing, stock, and categories.',
    fill_required_fields: 'Please fill in all required fields marked in red.',
    product_information: 'Product Information',
    product_code_label: 'Product Code',
    single_item_pricing_stock: 'Single Item Pricing & Stock',
    total_stock: 'Total Stock',
    normal_price: 'Normal Price ($)',
    agent_price: 'Agent Price ($)',
    promo_price: 'Promo Price ($)',
    per_box_pricing_optional: 'Per Box Pricing (Optional)',
    items_per_box: 'Items Per Box',
    box_price: 'Box Price ($)',
    box_agent_price: 'Box Agent Price ($)',
    box_promo_price: 'Box Promo Price ($)',
    bundle_set_pricing_optional: 'Bundle Set Pricing (Optional)',
    items_per_bundle: 'Items Per Bundle',
    bundle_price: 'Bundle Price ($)',
    bundle_agent_price: 'Bundle Agent Price ($)',
    bundle_promo_price: 'Bundle Promo Price ($)',
    visual_assets: 'Visual Assets',
    click_to_upload_images: 'Click to upload images',
    png_jpg_up_to_10mb: 'PNG, JPG up to 10MB',
    youtube_video_link_optional: 'Youtube Video Link (optional)',
    open_youtube: 'Open YouTube',
    how_to_add_video: 'How to Add Video',
    youtube_guide_step1: 'Click "Open YouTube" to visit youtube.com',
    youtube_guide_step2: 'Find and open the video you want to display',
    youtube_guide_step3: 'Copy the URL from the browser address bar',
    youtube_guide_step4: 'Paste the copied link into this input box',
    listing_status: 'Listing Status',
    confirm_upload: 'Confirm Upload',
    uploading: 'Uploading...',
    please_select_category: 'Please select a category.',
    please_provide_product_name: 'Please provide a product name.',
    please_upload_image: 'Please upload at least one image.',
    product_uploaded_successfully: 'Product uploaded successfully!',
    failed_to_upload_product: 'Failed to upload product. Please try again.',
    upload_single_item_page: 'Upload Single Item',
    available_products: 'Available Products',
    all: 'All',
    live: 'Live',
    hold: 'Hold',
    deactive: 'Deactive',
    low_stock: 'Low Stock',
    out_of_stock: 'Out of Stock',
    quick_action_subtitle: "You don't need to leave this page to make simple updates. To quickly edit an item:",
    double_click: 'Double-click',
    directly_on_the: 'directly on the',
    stock_price_status: 'Stock, Price, or Status',
    cells_in_inventory: 'cells in the inventory table below.',
    hit: 'Hit',
    enter: 'Enter',
    or_click_green_save: 'or click the green Save icon to instantly apply your changes!',
    got_it_thanks: 'Got it, Thanks!',
    prep_step2_pt1: 'Fill in all the required columns (marked with an asterisk',
    for_the: 'For the',
    image_filename: 'Image_Filename',
    column_input: 'column, input the exact filename of your image (e.g.,',
    firework_png: 'firework-01.png',
    note_on_folders: 'Note on Folders:',
    do_not_place_images: 'Our system utilizes a smart-scan engine. Folder names do not matter. We automatically search all directories within your ZIP archive to match filenames perfectly.',
    right_click_select: 'Right-click the folder and select',
    compress_to_zip: 'Compress to ZIP file',
    click: 'Click',
    confirm_import: 'Confirm Import',
    to_permanently_save: 'to permanently save the products to the database.',
    review_validation: 'Review any validation errors highlighted in red.',

    upload_single_item: 'Upload Single Item',
    bulk_upload: 'Bulk Upload',
    download_template: 'Download Template',
    bulk_upload_guidance: 'Bulk Upload Guidance',
    go_to_bulk_upload: 'Go to Bulk Upload',
    source_file: 'Source File',
    please_select_file: 'Please select a single file...',
    browse: 'Browse...',
    download_quick_import_template: 'Download quick import file',
    upload_btn: 'Upload',
    invalid_zip_err: 'Please upload a valid .zip file containing the Excel template and images.',
    available_on_store: 'Available on store',
    awaiting_action: 'Awaiting action',
    unpublished_items: 'Unpublished items',
    low_stock: 'Low Stock',
    below_10_items: 'Below 10 items',
    out_of_stock: 'Out of Stock',
    items_left: 'items left',
    best_least_selling: 'Best & Least Selling Products',
    see_which_products: 'See which products sold the most and the least this month',
    no_sales_data: 'No sales data for this month',
    product_stock_overview: 'Product Stock Overview',
    monitor_products: 'Monitor which products are available, running low, or sold out',
    inventory_list: 'Inventory List',
    permanent_deletion: 'Permanent Deletion',
    quick_action_guide: 'Quick Action Guide',
    inline_editing_shortcuts: 'Inline Editing Shortcuts',
    quick_action_step1: 'Double-click directly on the Stock, Price, or Status cells in the inventory table below.',
    quick_action_step2: 'Type your new value or select the new status from the dropdown.',
    quick_action_step3: 'Hit Enter or click the green Save icon to instantly apply your changes!',
    bulk_guide_intro: 'Welcome to the Bulk Upload guide. Our bulk import system allows you to easily upload hundreds of products and their corresponding images simultaneously using a single ZIP archive. Follow these professional guidelines to ensure a flawless data import experience.',
    prep_excel_template: 'Prepare the Excel Template',
    prep_step1: 'Begin by downloading the official template from the Products page.',
    prep_step2: 'Fill in all the required columns (marked with an asterisk *)',
    prep_step3: 'For the Image_Filename column, input the exact filename of your image (e.g., firework-01.png)',
    prep_step4: 'Ensure the spelling and file extension (.png, .jpg) matches your actual image file perfectly.',
    pack_zip_archive: 'Package the ZIP Archive',
    pack_step1: 'Consolidate your filled template and all product images into a single folder.',
    pack_step2: 'Note on Folders: Do not place images inside subfolders. Keep everything in the root folder.',
    pack_step3: 'Create a new folder on your computer.',
    pack_step4: 'Move your completed template and all related image files into this folder.',
    pack_step5: 'Right-click the folder and select Compress to ZIP file (Windows) or Compress (Mac).',
    upload_verify: 'Upload and Verify',
    upload_step1: 'Navigate to the Bulk Upload page and drop your newly created ZIP package.',
    upload_step2: 'The system will extract and analyze your ZIP package locally.',
    upload_step3: 'A preview table will appear showing exactly how your products will look.',
    upload_step4: 'Review any validation errors highlighted in red. Only flawless rows will be saved.',
    upload_step5: 'Click Confirm Import to permanently save the products to the database.',

    admin_title: 'Admin',
    super_admin: 'Super Admin',
    yes_logout: 'Yes, Log out',
    delete_category_title: 'Delete Category?',
    delete_category_q: 'Are you sure you want to delete',
    delete_category_warn: '? This action cannot be undone. All products under this category will lose their category association.',
    delete_category_btn: 'Delete Category',
    total_categories: 'Total Categories',
    organized_folders: 'Organized folders',
    across_all_categories: 'Across all categories',
    on_hold_category: 'On-Hold Category',
    hidden_from_frontend: 'Hidden from frontend',
    category_id: 'Category ID',
    category_name: 'Category Name',
    product_id: 'Product ID',
    product_name: 'Product Name',
    all: 'All',
    live: 'Live',
    hold: 'Hold',
    create_new_category: 'Create New Category',
    create_category_desc: 'Add a new product category to organize your inventory and help customers find products easily.',
    category_created: 'Category Created!',
    category_info: 'Category Information',
    category_code_url: 'Category Code (URL Key)',
    category_code_desc: 'Unique code for category URL (no spaces, use - or _)',
    chinese_translation_optional: 'Chinese Translation (optional)',
    display_order_optional: 'Display Order (optional)',
    lower_numbers_first: 'Lower numbers appear first',
    category_desc_optional: 'Category Description (optional)',
    hide_category_desc: 'Hide this category and all its products from the frontend.',
    category_photo: 'Category Photo',
    category_photo_desc: 'Upload a photo that represents this category',
    drag_drop_image: 'Drag & drop your image here',
    or_click_browse: 'or click to browse',
    image_restrictions: 'PNG, JPG, JPEG up to 10MB',
    image_preview: 'Image Preview',
    image_preview_desc: 'Image preview will appear here',
    tips: 'Tips',
    clear_image_tip: 'Use a clear image that best represents the category.',
    save_category: 'Save Category',
    edit_category: 'Edit Category',
    edit_category_desc: 'Modify the category details or update its visual assets.',
    category_updated: 'Category Updated!',
    update_category: 'Update Category',
    confirm_delete: 'Confirm Delete',
    delete_category_warn_2: 'After deletion, all products under this category will be hidden',
    saving: 'Saving...',
    add_new_product: 'Add New Product',
    delete_selected: 'Delete Selected',
    got_it: 'Got it',
    per_order: 'Per Order',
    total_items: 'Total Items',
    by_revenue_this_period: 'By revenue this period',
    units_sold_count: 'units sold',
    order_information: 'Order Information',
    total_orders_this_week: 'Total Order On This Week',
    recent_transactions: 'Recent Transactions',
    view_more: 'View More',
    cash_on_delivery: 'Cash On Delivery',
    duitnow_bank_transfer: 'DuitNow Bank Transfer',
    self_collect: 'Self Collect',
    delivery: 'Delivery',
    delivering: 'Delivering',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    products: 'Products',
    settings: 'Settings',
    customers: 'Customers',
    orders: 'Orders',
    total_customers: 'Total Customers',
    sellers: 'Sellers',
    guests: 'Guests',
    seller_setup: 'Seller Setup',
    business_setup: 'Business Setup',
    seller: 'Seller',
    guest: 'Guest',
    member: 'Member',
    discount: 'Discount',
    yes: 'Yes',
    no_label: 'No',
    customer_not_found: 'Customer not found.',
    back_to_customers: 'Back to Customers',
    back_to_customer: 'Back to Customer',
    back_to_list: 'Back to List',
    address: 'Address',
    no_address_provided: 'No address provided',
    registered_since: 'Registered Since',
    promote_to_seller: 'Promote to Seller',
    total_spent: 'Total Spent',
    order_history: 'Order History',
    latest_activity: 'Latest Activity',
    no_orders_yet: 'This customer hasn\'t placed any orders yet.',
    confirmation_dialog: 'Confirmation Dialog',
    promote_confirm_1: 'Are you sure you want to promote ',
    promote_confirm_2: ' to a Seller? They will gain access to exclusive supplier pricing.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    processing_dot: 'Processing...',
    retrieving_profile: 'Retrieving Profile...',
    syncing_profiles: 'Synchronizing Profiles...',
    no_customer_profiles_found: 'No matching customer profiles found.',
    total_products: 'Total Products',
    live_products: 'Live Products',
    total_orders: 'Total Orders',
    live_inventory: 'Live Inventory',
    active_products: 'Active Products',
    all_transactions: 'All Transactions',
    registered_customers: 'Total Customers',
    growth_members: 'Growth & Members',
    add_new_product: 'Add New Product',
    search_placeholder: 'Search products...',
    all_categories: 'All Categories',
    all_status: 'All Status',
    all_roles: 'All Roles',
    stock: 'Stock',
    price: 'Price',
    status: 'Status',
    delete_selected: 'Delete Selected',
    appearance: 'Visual Appearance',
    midnight_protocol: 'Midnight Protocol',
    daylight_clarity: 'Daylight Clarity',
    language_pref: 'Language Preference',
    english: 'English',
    chinese: 'Chinese',
    malay: 'Malay',
    save_settings: 'Save Settings',
    syncing: 'Synchronizing with database...',
    synced: 'Settings are synced across all sessions.',
    seller_levels: 'Seller Levels',
    sellers_list: 'Sellers List',
    add_level: 'Add Level',
    delete_level_confirm: 'Are you sure you want to delete this level? Sellers in this level will lose their benefits.',
    edit_level: 'Edit Level',
    new_seller_level: 'New Seller Level',
    level_name: 'Level Name',
    discount_percentage: 'Discount Percentage (%)',
    free_shipping_eligibility: 'Free Shipping Eligibility',
    save_level: 'Save Level',
    seller_setup_guide: 'Seller Setup Guide',
    silver_tier: 'Silver Tier (Level 1)',
    silver_tier_desc: 'Set up an entry-level tier for your new sellers. Typically, you can offer a ',
    five_percent_discount: '5% discount',
    on_all_products_without_fs: ' on all products without free shipping.',
    gold_tier: 'Gold Tier (Level 2)',
    gold_tier_desc: 'Create a mid-level tier to motivate your sellers. A good standard is a ',
    ten_percent_discount: '10% discount',
    on_all_products: ' on all products.',
    platinum_tier: 'Platinum Tier (Level 3)',
    platinum_tier_desc: 'Reward your top-performing sellers with the highest tier. Set it to a ',
    fifteen_percent_discount: '15% discount',
    and_enable: ' and enable ',
    free_shipping: 'Free Shipping',
    got_it: 'Got it',
    seller_name: 'Seller Name',
    performance: 'Performance',
    current_level: 'Current Level',
    actions: 'Actions',
    since: 'Since',
    no_level: 'No Level',
    suspended: 'Suspended',
    revoke_seller: 'Revoke Seller',
    no_sellers_found: 'No sellers found',
    system_overview: 'System Overview',
    system_preferences: 'System Preferences',
    system_preferences_desc: 'Manage your core business identity, contact information, and public links.',
    branding: 'Branding',
    business_name: 'Business Name',
    business_name_font: 'Business Name Font',
    preview: 'Preview',
    applied_to_header: 'Applied to header and footer business name',
    main_logo_image: 'Main Logo Image',
    change_logo: 'Change Logo',
    uploading: 'Uploading...',
    upload_logo: 'Upload Logo',
    transparent_logo: 'Transparent Logo',
    transparent_logo_tooltip: 'Used for watermarks on product images. Must be a PNG with a transparent background.',
    change_watermark: 'Change Watermark',
    upload_watermark: 'Upload Watermark',
    business_information: 'Business Information',
    phone_number: 'Phone Number',
    email_address: 'Email Address',
    whatsapp_number: 'WhatsApp Number',
    full_address: 'Full Address',
    social_media_links: 'Social Media Links',
    facebook_account: 'Facebook Account',
    instagram_handle: 'Instagram Handle',
    tiktok_handle: 'TikTok Handle',
    unsaved_changes: 'Unsaved changes',
    discard: 'Discard',
    confirm_settings: 'Confirm Settings',
    saving: 'Saving...',
    saved_successfully: 'Saved Successfully',
    saved_successfully_desc: 'Your business settings have been updated and are now live.',
    close: 'Close',
    revenue: 'Revenue',
    daily_revenue: 'Daily Revenue',
    top_selling_products: 'Top Selling Products',
    average_order_value: 'Average Order Value',
    total_sales: 'Total Sales',
    sales_metrics: 'Sales Metrics',
    last_30_days: 'Last 30 Days',
    units_sold: 'Units Sold',
    no_data: 'No data available',
    total_revenue: 'Total Revenue',
    completed_sales: 'Completed Sales',
    recent_transactions: 'Recent Transactions',
    market_split: 'Market Split',
    verified_sellers: 'Verified Sellers',
    regular_members: 'Regular Members',
    manage_customer_base: 'Manage Customer Base',
    view_inventory: 'View Inventory',
    members: 'Members',
    incoming: 'Pending',
    active_action: 'Active Action',
    fulfilled: 'Completed',
    cancelled: 'Cancelled',
    management: 'MANAGEMENT',
    view_more: 'View More',
    pending: 'Pending',
    in_process: 'In Process',
    completed: 'Completed',
    order_id: 'Order ID',
    total: 'Total',
    date: 'Date',
    click_to_manage: 'Click to manage',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    records: 'Records',
    page: 'Page',
    order_contents: 'Order Contents',
    customer_info: 'Customer Info',
    fulfillment_details: 'Fulfillment Details',
    order_control: 'Order Control',
    current_status: 'Current Status',
    save_changes: 'Save Changes',
    back_to_orders: 'Back to Orders',
    items: 'Items',
    subtotal: 'Subtotal',
    total_amount: 'Total Amount',
    processing: 'In Process',
    out_for_delivery: 'Delivering',
    name: 'Name',
    contact: 'Contact',
    shipping_address: 'Shipping Address',
    payment_method: 'Payment Method',
    fulfillment_mode: 'Fulfillment Mode',
    order_notes: 'Order Notes',
    order_placed: 'Order Placed',
    logout: 'Logout',
    no_recent_orders_found: 'No recent orders found.',
    scanning_order_records: 'Scanning Order Records...',
    no_order_records_found: 'No order records found.',
    order_record_not_found: 'Order Record Not Found.',
    loading_inventory: 'Loading Inventory...',
    no_products_found: 'No products match your filters.',
    order_id_tooltip: 'This ID represents the last 8 alphanumeric characters of the unique order identifier.',
    search_customers_placeholder: 'Search by name, phone or ID...',
    join_date: 'Join Date',
    phone: 'Phone',
    role: 'Role',
    customer: 'Customer',
    hold: 'Hold',
    deactive: 'Deactive',
    categories: 'Categories',
    add_new_category: 'Add New Category',
    export_csv: 'Export CSV',
    export_excel: 'Export Excel',
    export_pdf: 'Export PDF',
    out_of_stock: 'Out of Stock',
    low_stock: 'Low Stock',
    category_overview: 'Category Overview',
    upload_new_category: 'Upload New Category',
    upload_new_item: 'Upload New Item',
    visual_assets: 'Visual Assets',
    category_identity: 'Category Identity',
    product_identity: 'Product Identity',
    inventory_commerce: 'Inventory & Commerce',
    category_name_en: 'Category Name (English)',
    category_code: 'Category Code (URL Key)',
    please_input_category_name_auto_gen: 'Please input Category Name first to auto-generate code.',
    product_name_en: 'Product Name (English)',
    chinese_translation: 'Chinese Translation (optional)',
    malay_translation: 'Malay Translation (optional)',
    item_description: 'Item Description',
    quantity_stock: 'Quantity Stock',
    original_price: 'Original Price (RM)',
    seller_price: 'Seller Price (RM)',
    sale_price: 'Sale Price (RM)',
    auto_gen: 'Auto-Gen',
    choose_category: '-- Choose Category --',
    upload_banner: 'Upload Category Banner Image',
    click_select_images: 'Click to Select Multiple Images',
    add_more: 'Add More',
    youtube_link: 'YouTube Video Link',
    open_youtube: 'Open YouTube',
    confirm_upload: 'Confirm Upload',
    category_created: 'Category Created Successfully!',
    done_return: 'Done & Return to Inventory',
    selected_banner: 'Selected Banner Asset',
    how_to_add_video: 'How to Add Video',
    yt_step_1: 'Click "Open YouTube" to visit youtube.com',
    yt_step_2: 'Find and open the video you want to display',
    yt_step_3: 'Copy the URL from the browser address bar',
    yt_step_4: 'Paste the copied link into this input box',
    col_no: 'No.',
    col_code: 'Code',
    col_name: 'Name',
    col_category: 'Category',
    col_stock: 'Stock',
    col_original_price: 'Original Price (RM)',
    col_promotion_price: 'Promotion Price (RM)',
    col_seller_price: 'Seller Price (RM)',
    col_status: 'Status',
    pdf_english_only: 'PDF exports are always in English. Chinese/Malay characters are not supported by the built-in PDF font.',
    loading: 'Loading...',
    fetching_product_details: 'Fetching Product Details...',
    product_not_found: 'Product not found',
    confirm_delete_product: 'Are you sure you want to delete this product?',
    failed_delete_product: 'Failed to delete product',
    back_to_inventory: 'Back to Inventory',
    view_live_store: 'View Live Store',
    edit_product: 'Edit Product',
    edit_product_desc: 'Modify the product details, pricing, and status.',
    fill_required_fields_err: 'Please fill in all required fields marked in red.',
    product_info: 'Product Information',
    product_code: 'Product Code',
    auto_gen: 'Auto-Gen',
    single_pricing_stock: 'Single Item Pricing & Stock',
    total_stock: 'Total Stock',
    normal_price: 'Normal Price ($)',
    agent_price: 'Agent Price ($)',
    promo_price: 'Promo Price ($)',
    per_box_pricing: 'Per Box Pricing (Optional)',
    items_per_box: 'Items Per Box',
    box_price: 'Box Price ($)',
    box_agent_price: 'Box Agent Price ($)',
    box_promo_price: 'Box Promo Price ($)',
    bundle_pricing: 'Bundle Set Pricing (Optional)',
    items_per_bundle: 'Items Per Bundle',
    bundle_price: 'Bundle Price ($)',
    bundle_agent_price: 'Bundle Agent Price ($)',
    bundle_promo_price: 'Bundle Promo Price ($)',
    visual_assets: 'Visual Assets',
    click_to_upload_images: 'Click to upload images',
    image_size_hint: 'PNG, JPG up to 10MB',
    youtube_link_optional: 'Youtube Video Link (optional)',
    open_youtube: 'Open YouTube',
    how_to_add_video: 'How to Add Video',
    youtube_step1: 'Click "Open YouTube" to visit youtube.com',
    youtube_step2: 'Find and open the video you want to display',
    youtube_step3: 'Copy the URL from the browser address bar',
    youtube_step4: 'Paste the copied link into this input box',
    cancel: 'Cancel',
    save_changes: 'Save Changes',
    delete: 'Delete',
    stock_level: 'Stock Level',
    units: 'units',
    visibility: 'Visibility',
    pricing_structure: 'Pricing Structure',
    active_price: 'Active Price',
    you_save: 'You Save',
    base_price: 'Base Price',
    promo_price: 'Promo Price',
    last_updated: 'Last Updated',
    live_demonstration: 'Live Demonstration',
    product_demo: 'Product Demo',
    loading_product_data: 'Loading Product Data...',
    modify_product: 'Modify Product',
    listing_status: 'Listing Status',
    click_to_upload_images: 'Click to Upload New Images',
    cancel_changes: 'Cancel Changes',
    update_product_listing: 'Update Product Listing',
    please_upload_image: 'Please upload at least one image',
    please_select_category: 'Please select a category',
    product_code_required: 'Product code is required',
    failed_update_product: 'Failed to update product',
    failed_upload_images: 'Failed to upload images',
    please_input_name_auto_gen: 'Please input Product Name first to auto-generate code.',
    failed_auto_gen_code: 'Failed to auto-generate product code.',
    category: 'Category',
    product_code: 'Product Code',
    status_live: 'Live',
    status_hold: 'Hold',
    status_deactive: 'Deactive',
    err_image_required: 'Please upload at least one product image.',
    err_category_required: 'Please select a category.',
    err_code_required: 'Product code is required.',
    err_name_required: 'Product name is required.',
    err_stock_required: 'Stock quantity is required.',
    err_price_required: 'Original price is required.',
    clear_image_tip: 'Use a clear image that best represents the category.',
  },
  zh: {

    placed_on: '下单于',
    self_collect: '自提',
    delivery: '送货',
    edit_shipping_address: '编辑配送地址',
    resend_confirmation: '重新发送确认信',
    save_changes: '保存更改',
    cash_on_delivery: '货到付款',
    bank_transfer: '银行转账',
    qr_code: 'DuitNow 二维码',
    generate_receipt: '生成收据',
    status_tutorial_desc: '订单状态遵循严格的顺序流程以确保准确跟踪。您只能逐步推进订单状态。',
    type_message_placeholder: '输入给客户的信息...',
    email: '电子邮件',
    whatsapp: 'WhatsApp',
    sending: '发送中...',
    cannot: '不能',
    qm_processing: '处理中',
    qm_processing_text: '我们已收到您的订单，目前正在处理中。',
    qm_out_for_delivery: '配送中',
    qm_out_for_delivery_text: '好消息！您的订单已在配送途中。',
    qm_ready_for_pickup: '可自提',
    qm_ready_for_pickup_text: '您的订单已打包并准备好自提！',
    qm_delayed: '已延迟',
    qm_delayed_text: '您的订单略有延迟，我们将为您提供最新消息。',
    more_actions: '更多操作',
    edit_shipping_address: '编辑配送地址',
    refund_cancel_order: '退款 / 取消订单',
    order_status_title: '订单状态',
    payment_method_title: '付款方式',
    fulfillment_method_title: '履约方式',
    customer_info: '客户信息',
    shipping_address: '配送地址',
    payment_fulfillment: '付款与履约',
    view_receipt: '查看收据',
    payment_receipt: '付款收据',
    order_contents: '订单内容',
    subtotal: '小计',
    current: '当前',
    update_status_desc: '更新状态以让客户了解最新进展。',
    communication: '沟通',
    quick_messages: '快捷消息',
    whatsapp: 'WhatsApp',
    status_tutorial_title: '状态流程教程',
    status_tutorial_subtitle: '了解订单进展',
    status_tutorial_desc: '订单状态遵循严格的顺序流程，以确保准确跟踪。您只能一步一步地向前推进订单。',
    status_pending_desc: '已收到订单。等待管理员审核或付款确认。',
    status_in_process_desc: '订单已确认。商品正在包装和准备中。',
    status_delivering_desc: '包裹已出库配送或准备好让客户自提。',
    status_completed_desc: '已成功履约。无法采取进一步操作。',
    status_cancelled_desc: '订单在履约前被取消。库存可能会退回。',
    important_note: '重要提示：',
    cannot: '不能',
    be_cancelled_completed: ' 在达到已完成状态后取消。',
    success_exclaim: '成功！',
    continue_btn: '继续',
    update_address_desc: '更新此订单的配送地址。',
    cancel_order_q: '取消订单？',
    cancel_order_confirm: '您确定要取消此订单吗？',
    cancel_order_desc1: '产品库存将自动退回您的库存中。',
    cancel_order_desc2: '此操作无法撤销。',
    back: '返回',
    total_orders_today: '今日总订单',
    total_all_orders: '所有订单总数',
    order_completed_kpi: '已完成订单',
    in_process_order: '处理中订单',
    pending_order: '待处理订单',
    cancelled_order_kpi: '已取消订单',
    delivering_order: '配送中订单',
    bank_transfer: '银行转账',
    qr_code: 'DuitNow 二维码',
    cash_on_delivery: '货到付款',
    payment_methods: '付款方式',
    payment_methods_desc: '所有订单付款类型细分',
    no_payment_data: '暂无付款数据',
    filter_by_month: '按月份筛选',
    clear: '清除',
    apply: '应用',
    order_id: '订单编号',
    customer_name: '客户名称',
    phone_number: '电话号码',
    items: '商品数量',
    total_amount: '总金额',
    loading_orders: '加载订单中...',
    no_order_records: '未找到订单记录。',
    showing: '显示',
    records: '条记录',
    all_filter: '全部',
    pending_filter: '待处理',
    in_process_filter: '处理中',
    delivering_filter: '配送中',
    completed_filter: '已完成',
    cancelled_filter: '已取消',
    search_orders_placeholder: '搜索订单编号，客户名称...',
    total: '总计',
    orders_list: '订单列表',
    edit_product_desc: '修改产品详情、定价和状态。',
    fill_required_fields_err: '请填写所有标红的必填字段。',
    product_info: '产品信息',
    product_code: '产品代码',
    auto_gen: '自动生成',
    single_pricing_stock: '单件定价和库存',
    total_stock: '总库存',
    normal_price: '原价 ($)',
    agent_price: '代理价 ($)',
    promo_price: '促销价 ($)',
    per_box_pricing: '整箱定价 (可选)',
    items_per_box: '每箱数量',
    box_price: '整箱价 ($)',
    box_agent_price: '整箱代理价 ($)',
    box_promo_price: '整箱促销价 ($)',
    bundle_pricing: '捆绑套装定价 (可选)',
    items_per_bundle: '每套数量',
    bundle_price: '套装价 ($)',
    bundle_agent_price: '套装代理价 ($)',
    bundle_promo_price: '套装促销价 ($)',
    visual_assets: '视觉资产',
    click_to_upload_images: '点击上传图片',
    image_size_hint: 'PNG, JPG 最大 10MB',
    youtube_link_optional: 'Youtube 视频链接 (可选)',
    open_youtube: '打开 YouTube',
    how_to_add_video: '如何添加视频',
    youtube_step1: '点击“打开 YouTube”访问 youtube.com',
    youtube_step2: '找到并打开您想要展示的视频',
    youtube_step3: '从浏览器地址栏复制网址',
    youtube_step4: '将复制的链接粘贴到此输入框中',
    cancel: '取消',
    save_changes: '保存更改',
    import_completed: '导入完成',
    bulk_upload_processed: '您的批量上传已处理。',
    success_label: '成功',
    failed_label: '失败',
    error_details: '错误详情',
    return_to_inventory: '返回库存',
    importing_products: '正在导入产品',
    importing_products_desc: '请稍候，我们正在上传您的图片并将产品数据保存到数据库中。这可能需要几分钟时间。',
    upload_package: '上传压缩包',
    upload_package_desc: '压缩包必须包含填写完毕的 Excel 模板及所有相关的产品图片。',
    dont_have_template: '还没有官方模板？',
    preview_validation_title: '预览和验证',
    row: '行',
    image: '图片',
    missing: '缺失',
    reupload: '重新上传',
    upload_zip_msg: '请上传包含 Excel 和图片的 ZIP 文件。',
    read_zip_err: '读取 ZIP 文件失败',
    no_excel_err: '在 ZIP 压缩包中未找到 Excel 文件 (.xlsx)。',
    empty_excel_err: 'Excel 文件为空。',
    process_products_err: '处理产品失败',
    no_valid_products: '未找到要导入的有效产品。',
    products_text: '产品',
    found: '发现',
    issues: '个问题',
    importing: '导入中',
    description_en: '描述（英文）',
    eg_thunder_clap: '例如 Thunder Clap',
    eg_thunder_clap_zh: '例如 雷霆万钧',
    eg_tc00001: '例如 TC00001',
    product_details_ph: '产品详情...',
    product_details_zh_ph: '产品详情...',
    choose_category: '选择分类',
    upload_new_product_desc: '在库存中添加新产品，并设置其定价、库存和分类。',
    fill_required_fields: '请填写所有标有红色的必填字段。',
    product_information: '产品信息',
    product_code_label: '产品代码',
    single_item_pricing_stock: '单品定价和库存',
    total_stock: '总库存',
    normal_price: '原价 ($)',
    agent_price: '代理价 ($)',
    promo_price: '促销价 ($)',
    per_box_pricing_optional: '每盒定价（可选）',
    items_per_box: '每盒数量',
    box_price: '盒价 ($)',
    box_agent_price: '盒代理价 ($)',
    box_promo_price: '盒促销价 ($)',
    bundle_set_pricing_optional: '套装定价（可选）',
    items_per_bundle: '每套数量',
    bundle_price: '套装价 ($)',
    bundle_agent_price: '套装代理价 ($)',
    bundle_promo_price: '套装促销价 ($)',
    visual_assets: '视觉资产',
    click_to_upload_images: '点击上传图片',
    png_jpg_up_to_10mb: 'PNG, JPG 最大 10MB',
    youtube_video_link_optional: 'Youtube 视频链接（可选）',
    open_youtube: '打开 YouTube',
    how_to_add_video: '如何添加视频',
    youtube_guide_step1: '点击“打开 YouTube”访问 youtube.com',
    youtube_guide_step2: '找到并打开您要显示的视频',
    youtube_guide_step3: '从浏览器地址栏复制 URL',
    youtube_guide_step4: '将复制的链接粘贴到此输入框中',
    listing_status: '上架状态',
    confirm_upload: '确认上传',
    uploading: '上传中...',
    please_select_category: '请选择一个分类。',
    please_provide_product_name: '请提供产品名称。',
    please_upload_image: '请至少上传一张图片。',
    product_uploaded_successfully: '产品上传成功！',
    failed_to_upload_product: '上传产品失败。请重试。',
    upload_single_item_page: '上传单品',
    available_products: '可用商品',
    all: '全部',
    live: '在售',
    hold: '暂扣',
    deactive: '已停用',
    low_stock: '库存不足',
    out_of_stock: '缺货',
    quick_action_subtitle: '您无需离开此页面即可进行简单的更新。要快速编辑项目：',
    double_click: '双击',
    directly_on_the: '直接在下面的库存表中的',
    stock_price_status: '库存、价格或状态',
    cells_in_inventory: '单元格上。',
    hit: '按',
    enter: 'Enter',
    or_click_green_save: '或点击绿色的保存图标即可立即应用您的更改！',
    got_it_thanks: '明白了，谢谢！',
    prep_step2_pt1: '填写所有必填列（标有星号',
    for_the: '对于',
    image_filename: 'Image_Filename',
    column_input: '列，请输入您图像的准确文件名（例如：',
    firework_png: 'firework-01.png',
    note_on_folders: '文件夹注意事项：',
    do_not_place_images: '我们的系统利用智能扫描引擎。文件夹名称无关紧要。我们会自动搜索您 ZIP 压缩包中的所有目录，以完美匹配文件名。',
    right_click_select: '右键单击文件夹并选择',
    compress_to_zip: '压缩为 ZIP 文件',
    click: '单击',
    confirm_import: '确认导入',
    to_permanently_save: '以将产品永久保存到数据库中。',
    review_validation: '检查以红色突出显示的任何验证错误。',

    upload_single_item: '上传单个商品',
    bulk_upload: '批量上传',
    download_template: '下载模板',
    bulk_upload_guidance: '批量上传指南',
    go_to_bulk_upload: '前往批量上传',
    source_file: '來源檔案',
    please_select_file: '請選擇 單一檔案...',
    browse: '瀏覽...',
    download_quick_import_template: '下載快速鍵匯入檔',
    upload_btn: '上傳',
    invalid_zip_err: '請上傳包含 Excel 模板和圖片的有效 .zip 文件。',
    available_on_store: '商店在售',
    awaiting_action: '等待处理',
    unpublished_items: '未发布的商品',
    low_stock: '库存不足',
    below_10_items: '少于 10 件',
    out_of_stock: '缺货',
    items_left: '件剩余',
    best_least_selling: '最畅销和滞销商品',
    see_which_products: '查看本月销量最高和最低的商品',
    no_sales_data: '本月无销售数据',
    product_stock_overview: '商品库存概览',
    monitor_products: '监控哪些商品可用、库存不足或已售罄',
    inventory_list: '库存列表',
    permanent_deletion: '永久删除',
    quick_action_guide: '快速操作指南',
    inline_editing_shortcuts: '内联编辑快捷键',
    quick_action_step1: '双击下面库存表中的库存、价格或状态单元格。',
    quick_action_step2: '输入新值或从下拉列表中选择新状态。',
    quick_action_step3: '按 Enter 键或点击绿色的保存图标即可立即应用您的更改！',
    bulk_guide_intro: '欢迎使用批量上传指南。我们的批量导入系统允许您使用单个 ZIP 压缩包同时轻松上传数百个产品及其相应的图像。请遵循这些专业指南以确保完美的数据导入体验。',
    prep_excel_template: '准备 Excel 模板',
    prep_step1: '首先从“产品”页面下载官方模板。',
    prep_step2: '填写所有必填列（标有星号 *）',
    prep_step3: '对于 Image_Filename 列，请输入您图像的准确文件名（例如：firework-01.png）',
    prep_step4: '确保拼写和文件扩展名（.png、.jpg）与实际图像文件完全匹配。',
    pack_zip_archive: '打包 ZIP 压缩包',
    pack_step1: '将填好的模板和所有产品图像整合到一个文件夹中。',
    pack_step2: '文件夹注意事项：不要将图像放在子文件夹中。把所有东西放在根文件夹中。',
    pack_step3: '在电脑上创建一个新文件夹。',
    pack_step4: '将您完成的模板和所有相关的图像文件移到此文件夹中。',
    pack_step5: '右键单击文件夹并选择“压缩为 ZIP 文件”（Windows）或“压缩”（Mac）。',
    upload_verify: '上传并验证',
    upload_step1: '导航到“批量上传”页面，放入新创建的 ZIP 压缩包。',
    upload_step2: '系统将在本地提取并分析您的 ZIP 包。',
    upload_step3: '将出现一个预览表，准确显示您的产品外观。',
    upload_step4: '检查以红色突出显示的任何验证错误。只会保存无误的行。',
    upload_step5: '单击“确认导入”以将产品永久保存到数据库中。',

    admin_title: '管理员',
    super_admin: '超级管理员',
    yes_logout: '是，退出',
    delete_category_title: '删除分类？',
    delete_category_q: '您确定要删除',
    delete_category_warn: '？此操作无法撤消。该分类下的所有产品都将失去其分类关联。',
    delete_category_btn: '删除分类',
    total_categories: '总分类数',
    organized_folders: '已整理文件夹',
    across_all_categories: '所有分类中的产品',
    on_hold_category: '暂停的分类',
    hidden_from_frontend: '从前端隐藏',
    category_id: '分类 ID',
    category_name: '分类名称',
    product_id: '商品 ID',
    product_name: '商品名称',
    all: '全部',
    live: '上架',
    hold: '暂停',
    create_new_category: '创建新分类',
    create_category_desc: '添加新产品分类以整理您的库存并帮助客户轻松查找产品。',
    category_created: '分类已创建！',
    category_info: '分类信息',
    category_code_url: '分类代码 (URL 键)',
    category_code_desc: '分类 URL 的唯一代码（无空格，使用 - 或 _）',
    chinese_translation_optional: '中文翻译（可选）',
    display_order_optional: '显示顺序（可选）',
    lower_numbers_first: '数字越小越靠前',
    category_desc_optional: '分类描述（可选）',
    hide_category_desc: '从前端隐藏此分类及其所有产品。',
    category_photo: '分类照片',
    category_photo_desc: '上传代表此分类的照片',
    drag_drop_image: '将图像拖放到此处',
    or_click_browse: '或点击浏览',
    image_restrictions: 'PNG, JPG, JPEG 最高 10MB',
    image_preview: '图像预览',
    image_preview_desc: '图像预览将显示在此处',
    tips: '提示',
    clear_image_tip: '使用能够最好地代表该分类的清晰图像。',
    save_category: '保存分类',
    edit_category: '编辑分类',
    edit_category_desc: '修改分类详细信息或更新其视觉资产。',
    category_updated: '分类已更新！',
    update_category: '更新分类',
    confirm_delete: '确认删除',
    delete_category_warn_2: '删除后，该分类下的所有产品都将被隐藏',
    saving: '保存中...',
    add_new_product: '添加新商品',
    delete_selected: '删除选中项',
    got_it: '知道了',
    per_order: '每单',
    total_items: '总项目',
    by_revenue_this_period: '按此期间的收入',
    units_sold_count: '件售出',
    order_information: '订单信息',
    total_orders_this_week: '本周总订单',
    recent_transactions: '最近交易',
    view_more: '查看更多',
    cash_on_delivery: '货到付款',
    duitnow_bank_transfer: 'DuitNow 银行转账',
    self_collect: '自取',
    delivery: '外送',
    delivering: '配送中',
    dashboard: '仪表盘',
    inventory: '库存管理',
    products: '产品',
    settings: '设置',
    customers: '客户',
    orders: '订单管理',
    total_customers: '客户总数',
    sellers: '卖家',
    guests: '游客',
    seller_setup: '卖家设置',
    business_setup: '商家设置',
    seller: '卖家',
    guest: '游客',
    member: '会员',
    discount: '折扣',
    yes: '是',
    no_label: '否',
    customer_not_found: '未找到客户。',
    back_to_customers: '返回客户列表',
    back_to_customer: '返回客户资料',
    back_to_list: '返回列表',
    address: '地址',
    no_address_provided: '未提供地址',
    registered_since: '注册日期',
    promote_to_seller: '升级为卖家',
    total_spent: '总消费',
    order_history: '历史订单',
    latest_activity: '最新动态',
    no_orders_yet: '该客户尚未下任何订单。',
    confirmation_dialog: '确认对话框',
    promote_confirm_1: '您确定要将 ',
    promote_confirm_2: ' 升级为卖家吗？他们将获得专属的供应商价格。',
    cancel: '取消',
    confirm: '确认',
    processing_dot: '处理中...',
    retrieving_profile: '获取个人资料...',
    syncing_profiles: '正在同步资料...',
    no_customer_profiles_found: '未找到匹配的客户资料。',
    total_products: '产品总数',
    live_products: '上架产品',
    total_orders: '订单总数',
    live_inventory: '实时库存',
    active_products: '活跃产品',
    all_transactions: '所有交易',
    registered_customers: '注册客户',
    growth_members: '增长与会员',
    add_new_product: '添加新产品',
    search_placeholder: '搜索产品...',
    all_categories: '所有类别',
    all_status: '所有状态',
    all_roles: '所有角色',
    stock: '库存',
    price: '价格',
    status: '状态',
    delete_selected: '删除选中项',
    appearance: '视觉外观',
    midnight_protocol: '午夜模式',
    daylight_clarity: '白昼模式',
    language_pref: '语言偏好',
    english: '英文',
    chinese: '中文',
    malay: '马来文',
    save_settings: '保存设置',
    syncing: '正在同步到数据库...',
    synced: '设置已在所有会话中同步。',
    seller_levels: '卖家等级',
    sellers_list: '卖家列表',
    add_level: '添加等级',
    delete_level_confirm: '确定要删除此等级吗？此等级下的卖家将失去其福利。',
    edit_level: '编辑等级',
    new_seller_level: '新建卖家等级',
    level_name: '等级名称',
    discount_percentage: '折扣百分比 (%)',
    free_shipping_eligibility: '免运费资格',
    save_level: '保存等级',
    seller_setup_guide: '卖家设置指南',
    silver_tier: '白银等级 (1 级)',
    silver_tier_desc: '为您的新卖家设置入门等级。通常，您可以提供 ',
    five_percent_discount: '5% 的折扣',
    on_all_products_without_fs: '，不含免运费。',
    gold_tier: '黄金等级 (2 级)',
    gold_tier_desc: '创建一个中等等级来激励您的卖家。一个很好的标准是 ',
    ten_percent_discount: '10% 的折扣',
    on_all_products: '。',
    platinum_tier: '白金等级 (3 级)',
    platinum_tier_desc: '用最高等级奖励您表现最好的卖家。将其设置为 ',
    fifteen_percent_discount: '15% 的折扣',
    and_enable: ' 并启用',
    free_shipping: '免运费',
    got_it: '知道了',
    seller_name: '卖家名称',
    performance: '表现',
    current_level: '当前等级',
    actions: '操作',
    since: '自',
    no_level: '无等级',
    suspended: '已暂停',
    revoke_seller: '撤销卖家身份',
    no_sellers_found: '未找到卖家',
    system_overview: '系统概览',
    system_preferences: '系统偏好设置',
    system_preferences_desc: '管理您的核心业务标识、联系信息和公共链接。',
    branding: '品牌建设',
    business_name: '商家名称',
    business_name_font: '商家名称字体',
    preview: '预览',
    applied_to_header: '应用于页眉和页脚的商家名称',
    main_logo_image: '主标志图片',
    change_logo: '更改标志',
    uploading: '上传中...',
    upload_logo: '上传标志',
    transparent_logo: '透明标志',
    transparent_logo_tooltip: '用于产品图片上的水印。必须是透明背景的 PNG 格式。',
    change_watermark: '更改水印',
    upload_watermark: '上传水印',
    business_information: '商家信息',
    phone_number: '电话号码',
    email_address: '电子邮件地址',
    whatsapp_number: 'WhatsApp 号码',
    full_address: '完整地址',
    social_media_links: '社交媒体链接',
    facebook_account: 'Facebook 账号',
    instagram_handle: 'Instagram 账号',
    tiktok_handle: 'TikTok 账号',
    unsaved_changes: '未保存的更改',
    discard: '放弃',
    confirm_settings: '确认设置',
    saving: '保存中...',
    saved_successfully: '保存成功',
    saved_successfully_desc: '您的商家设置已更新并生效。',
    close: '关闭',
    revenue: '收入',
    daily_revenue: '每日收入',
    top_selling_products: '畅销产品',
    average_order_value: '平均订单价值',
    total_sales: '总销售额',
    sales_metrics: '销售指标',
    last_30_days: '过去 30 天',
    units_sold: '售出数量',
    no_data: '暂无数据',
    total_revenue: '总收入',
    completed_sales: '已完成销售',
    recent_transactions: '最近交易',
    market_split: '市场分布',
    verified_sellers: '认证卖家',
    regular_members: '普通会员',
    manage_customer_base: '管理客户群',
    view_inventory: '查看库存',
    members: '会员',
    incoming: '待处理',
    active_action: '正在处理',
    fulfilled: '已完成',
    cancelled: '已取消',
    management: '管理',
    view_more: '查看更多',
    pending: '待处理',
    in_process: '处理中',
    completed: '已完成',
    order_id: '订单编号',
    total: '总额',
    date: '日期',
    click_to_manage: '点击管理',
    showing: '显示',
    to: '至',
    of: '共',
    records: '条记录',
    page: '第',
    order_contents: '订单内容',
    customer_info: '客户信息',
    fulfillment_details: '履行详情',
    order_control: '订单控制',
    current_status: '当前状态',
    save_changes: '保存修改',
    back_to_orders: '返回订单列表',
    items: '件商品',
    subtotal: '小计',
    total_amount: '总金额',
    processing: '正在处理',
    out_for_delivery: '正在派送',
    name: '名称',
    contact: '联系方式',
    shipping_address: '收货地址',
    payment_method: '支付方式',
    fulfillment_mode: '履行模式',
    order_notes: '订单备注',
    order_placed: '下单时间',
    logout: '退出登录',
    no_recent_orders_found: '未找到近期订单。',
    scanning_order_records: '正在扫描订单记录...',
    no_order_records_found: '未找到订单记录。',
    order_record_not_found: '找不到订单记录。',
    loading_inventory: '正在加载库存...',
    no_products_found: '没有找到符合条件的产品。',
    order_id_tooltip: '此编号代表唯一订单标识符的最后 8 位字母数字字符。',
    search_customers_placeholder: '搜索名称、电话或ID...',
    join_date: '加入日期',
    phone: '电话',
    role: '角色',
    customer: '客户',
    hold: '暂停',
    deactive: '已下架',
    categories: '分类',
    add_new_category: '添加新分类',
    export_csv: '导出 CSV',
    export_excel: '导出 Excel',
    export_pdf: '导出 PDF',
    out_of_stock: '缺货',
    low_stock: '库存不足',
    category_overview: '分类概览',
    upload_new_category: '上传新分类',
    upload_new_item: '上传新产品',
    visual_assets: '视觉资源',
    category_identity: '分类信息',
    product_identity: '产品信息',
    inventory_commerce: '库存与商业',
    category_name_en: '分类名称（英文）',
    category_code: '分类代码',
    please_input_category_name_auto_gen: '请先输入分类名称以自动生成代码。',
    product_name_en: '产品名称（英文）',
    chinese_translation: '中文翻译（可选）',
    malay_translation: '马来文翻译（可选）',
    item_description: '产品描述',
    quantity_stock: '库存数量',
    original_price: '原价 (RM)',
    seller_price: '卖家价 (RM)',
    sale_price: '促销价 (RM)',
    auto_gen: '自动生成',
    choose_category: '-- 选择分类 --',
    upload_banner: '上传分类封面图片',
    click_select_images: '点击选择多张图片',
    add_more: '继续添加',
    youtube_link: 'YouTube 视频链接',
    open_youtube: '打开 YouTube',
    confirm_upload: '确认上传',
    category_created: '分类创建成功！',
    done_return: '完成并返回库存',
    selected_banner: '已选封面图片',
    how_to_add_video: '如何添加视频',
    yt_step_1: '点击「打开 YouTube」访问 youtube.com',
    yt_step_2: '找到并打开您要显示的视频',
    yt_step_3: '从浏览器地址栏复制链接',
    yt_step_4: '将复制的链接粘贴到输入框中',
    col_no: '编号',
    col_code: '代码',
    col_name: '名称',
    col_category: '分类',
    col_stock: '库存',
    col_original_price: '原价 (RM)',
    col_promotion_price: '促销价 (RM)',
    col_seller_price: '卖家价 (RM)',
    col_status: '状态',
    pdf_english_only: 'PDF 导出时始终使用英文。PDF 内置字体不支持中文字符，如需中文表格请使用 Excel 导出。',
    loading: '加载中...',
    fetching_product_details: '获取产品详情中...',
    product_not_found: '未找到该产品',
    confirm_delete_product: '您确定要删除这个产品吗？',
    failed_delete_product: '删除产品失败',
    back_to_inventory: '返回库存列表',
    view_live_store: '查看线上店铺',
    edit_product: '编辑产品',
    delete: '删除',
    stock_level: '库存水平',
    units: '件',
    visibility: '可见性',
    pricing_structure: '价格结构',
    active_price: '当前价格',
    you_save: '您节省',
    base_price: '底价',
    promo_price: '促销价',
    last_updated: '最后更新',
    live_demonstration: '实物演示',
    product_demo: '产品演示',
    loading_product_data: '加载产品数据中...',
    modify_product: '修改产品',
    listing_status: '产品状态',
    click_to_upload_images: '点击上传新图片',
    cancel_changes: '取消修改',
    update_product_listing: '更新产品列表',
    please_upload_image: '请上传至少一张图片',
    please_select_category: '请选择分类',
    product_code_required: '产品代码是必填的',
    failed_update_product: '更新产品失败',
    failed_upload_images: '上传图片失败',
    please_input_name_auto_gen: '请先输入产品名称以自动生成代码。',
    failed_auto_gen_code: '自动生成产品代码失败。',
    category: '分类',
    product_code: '产品代码',
    status_live: '上架',
    status_hold: '暂停',
    status_deactive: '下架',
    err_image_required: '请上传至少一张产品图片。',
    err_category_required: '请选择分类。',
    err_code_required: '产品代码为必填项。',
    err_name_required: '产品名称为必填项。',
    err_stock_required: '库存数量为必填项。',
    err_price_required: '原价为必填项。',
  },
  ms: {

    placed_on: 'Dipesan pada',
    self_collect: 'Ambil Sendiri',
    delivery: 'Penghantaran',
    edit_shipping_address: 'Edit Alamat Penghantaran',
    resend_confirmation: 'Hantar Semula Pengesahan',
    save_changes: 'Simpan perubahan',
    cash_on_delivery: 'Tunai Semasa Penghantaran',
    bank_transfer: 'Pindahan Bank',
    qr_code: 'Kod QR DuitNow',
    generate_receipt: 'Jana Resit',
    status_tutorial_desc: 'Status pesanan mengikut aliran berurutan yang ketat untuk memastikan pengesanan tepat. Anda hanya boleh memajukan pesanan selangkah demi selangkah.',
    type_message_placeholder: 'Taip mesej kepada pelanggan...',
    email: 'E-mel',
    whatsapp: 'WhatsApp',
    sending: 'Sedang menghantar...',
    cannot: 'tidak boleh',
    qm_processing: 'Sedang Diproses',
    qm_processing_text: 'Kami telah menerima pesanan anda dan sedang memprosesnya.',
    qm_out_for_delivery: 'Sedang Dihantar',
    qm_out_for_delivery_text: 'Berita baik! Pesanan anda sedang dihantar.',
    qm_ready_for_pickup: 'Sedia untuk Diambil',
    qm_ready_for_pickup_text: 'Pesanan anda telah dibungkus dan sedia untuk diambil!',
    qm_delayed: 'Tertunda',
    qm_delayed_text: 'Terdapat sedikit kelewatan dengan pesanan anda, kami akan memaklumkan perkembangannya.',
    more_actions: 'Lebih banyak tindakan',
    edit_shipping_address: 'Edit Alamat Penghantaran',
    refund_cancel_order: 'Bayar Balik / Batal Pesanan',
    order_status_title: 'Status Pesanan',
    payment_method_title: 'Kaedah Pembayaran',
    fulfillment_method_title: 'Kaedah Pemenuhan',
    customer_info: 'Maklumat Pelanggan',
    shipping_address: 'Alamat Penghantaran',
    payment_fulfillment: 'Pembayaran & Pemenuhan',
    view_receipt: 'Lihat resit',
    payment_receipt: 'Resit Pembayaran',
    order_contents: 'Kandungan Pesanan',
    subtotal: 'Jumlah Kecil',
    current: 'Semasa',
    update_status_desc: 'Kemas kini status untuk memberitahu pelanggan anda.',
    communication: 'Komunikasi',
    quick_messages: 'Mesej Pantas',
    whatsapp: 'WhatsApp',
    status_tutorial_title: 'Tutorial Aliran Status',
    status_tutorial_subtitle: 'Memahami Perkembangan Pesanan',
    status_tutorial_desc: 'Status pesanan mengikut aliran berurutan yang ketat untuk memastikan penjejakan yang tepat. Anda hanya boleh memajukan pesanan selangkah demi selangkah.',
    status_pending_desc: 'Pesanan diterima. Menunggu semakan admin atau pengesahan pembayaran.',
    status_in_process_desc: 'Pesanan disahkan. Item sedang dibungkus dan disediakan.',
    status_delivering_desc: 'Pakej sedang dihantar atau sedia untuk diambil oleh pelanggan.',
    status_completed_desc: 'Berjaya dipenuhi. Tiada tindakan lanjut boleh diambil.',
    status_cancelled_desc: 'Pesanan dibatalkan sebelum dipenuhi. Stok mungkin akan dikembalikan.',
    important_note: 'Nota Penting:',
    cannot: 'tidak boleh',
    be_cancelled_completed: ' dibatalkan setelah mencapai status Selesai.',
    success_exclaim: 'Berjaya!',
    continue_btn: 'Teruskan',
    update_address_desc: 'Kemas kini alamat penghantaran untuk pesanan ini.',
    cancel_order_q: 'Batal Pesanan?',
    cancel_order_confirm: 'Adakah anda pasti ingin membatalkan pesanan ini?',
    cancel_order_desc1: 'Stok produk akan dikembalikan secara automatik ke inventori anda.',
    cancel_order_desc2: 'Tindakan ini tidak boleh dibuat semula.',
    back: 'Kembali',
    total_orders_today: 'Jumlah Pesanan Hari Ini',
    total_all_orders: 'Jumlah Semua Pesanan',
    order_completed_kpi: 'Pesanan Selesai',
    in_process_order: 'Pesanan Dalam Proses',
    pending_order: 'Pesanan Tertunda',
    cancelled_order_kpi: 'Pesanan Dibatalkan',
    delivering_order: 'Pesanan Sedang Dihantar',
    bank_transfer: 'Pemindahan Bank',
    qr_code: 'Kod QR DuitNow',
    cash_on_delivery: 'Tunai Semasa Penghantaran (COD)',
    payment_methods: 'Kaedah Pembayaran',
    payment_methods_desc: 'Pecahan semua jenis pembayaran pesanan',
    no_payment_data: 'Tiada data pembayaran',
    filter_by_month: 'Tapis ikut Bulan',
    clear: 'Kosongkan',
    apply: 'Gunakan',
    order_id: 'ID Pesanan',
    customer_name: 'Nama Pelanggan',
    phone_number: 'Nombor Telefon',
    items: 'Item',
    total_amount: 'Jumlah',
    loading_orders: 'Memuatkan Pesanan...',
    no_order_records: 'Tiada rekod pesanan ditemui.',
    showing: 'Menunjukkan',
    records: 'rekod',
    all_filter: 'Semua',
    pending_filter: 'Tertunda',
    in_process_filter: 'Dalam Proses',
    delivering_filter: 'Sedang Dihantar',
    completed_filter: 'Selesai',
    cancelled_filter: 'Dibatalkan',
    search_orders_placeholder: 'Cari ID pesanan, nama pelanggan...',
    total: 'Jumlah',
    orders_list: 'Senarai Pesanan',
    edit_product_desc: 'Ubah butiran produk, harga, dan status.',
    fill_required_fields_err: 'Sila isikan semua medan wajib yang ditanda merah.',
    product_info: 'Maklumat Produk',
    product_code: 'Kod Produk',
    auto_gen: 'Jana Auto',
    single_pricing_stock: 'Harga & Stok Item Tunggal',
    total_stock: 'Jumlah Stok',
    normal_price: 'Harga Biasa ($)',
    agent_price: 'Harga Ejen ($)',
    promo_price: 'Harga Promosi ($)',
    per_box_pricing: 'Harga Setiap Kotak (Pilihan)',
    items_per_box: 'Item Setiap Kotak',
    box_price: 'Harga Kotak ($)',
    box_agent_price: 'Harga Ejen Kotak ($)',
    box_promo_price: 'Harga Promosi Kotak ($)',
    bundle_pricing: 'Harga Set Berkas (Pilihan)',
    items_per_bundle: 'Item Setiap Berkas',
    bundle_price: 'Harga Berkas ($)',
    bundle_agent_price: 'Harga Ejen Berkas ($)',
    bundle_promo_price: 'Harga Promosi Berkas ($)',
    visual_assets: 'Aset Visual',
    click_to_upload_images: 'Klik untuk memuat naik imej',
    image_size_hint: 'PNG, JPG sehingga 10MB',
    youtube_link_optional: 'Pautan Video Youtube (pilihan)',
    open_youtube: 'Buka YouTube',
    how_to_add_video: 'Cara Menambah Video',
    youtube_step1: 'Klik "Buka YouTube" untuk melawat youtube.com',
    youtube_step2: 'Cari dan buka video yang ingin anda paparkan',
    youtube_step3: 'Salin URL dari bar alamat penyemak imbas',
    youtube_step4: 'Tampal pautan yang disalin ke dalam kotak input ini',
    cancel: 'Batal',
    save_changes: 'Simpan Perubahan',
    import_completed: 'Import Selesai',
    bulk_upload_processed: 'Muat naik pukal anda telah diproses.',
    success_label: 'Berjaya',
    failed_label: 'Gagal',
    error_details: 'Butiran Ralat',
    return_to_inventory: 'Kembali ke Inventori',
    importing_products: 'Mengimport Produk',
    importing_products_desc: 'Sila tunggu sementara kami memuat naik imej anda dan menyimpan data produk ke pangkalan data. Ini mungkin mengambil masa beberapa saat.',
    upload_package: 'Muat Naik Pakej',
    upload_package_desc: 'Pakej mesti mengandungi templat Excel yang telah diisi dan semua imej produk yang berkaitan.',
    dont_have_template: 'Belum mempunyai templat rasmi?',
    preview_validation_title: 'Pratonton & Pengesahan',
    row: 'Baris',
    image: 'Imej',
    missing: 'Hilang',
    reupload: 'Muat naik semula',
    upload_zip_msg: 'Sila muat naik fail ZIP yang mengandungi excel dan imej.',
    read_zip_err: 'Gagal membaca fail ZIP',
    no_excel_err: 'Tiada fail Excel (.xlsx) ditemui dalam pakej ZIP.',
    empty_excel_err: 'Fail Excel adalah kosong.',
    process_products_err: 'Gagal memproses produk',
    no_valid_products: 'Tiada produk sah ditemui untuk diimport.',
    products_text: 'Produk',
    found: 'Ditemui',
    issues: 'Isu',
    importing: 'Mengimport',
    description_en: 'Penerangan (Inggeris)',
    eg_thunder_clap: 'cth. Thunder Clap',
    eg_thunder_clap_zh: 'cth. 雷霆万钧',
    eg_tc00001: 'cth. TC00001',
    product_details_ph: 'Butiran produk...',
    product_details_zh_ph: '产品详情...',
    choose_category: 'Pilih Kategori',
    upload_new_product_desc: 'Tambah produk baharu ke inventori anda dan tetapkan harga, stok, dan kategorinya.',
    fill_required_fields: 'Sila isi semua medan yang diperlukan yang ditandakan dengan warna merah.',
    product_information: 'Maklumat Produk',
    product_code_label: 'Kod Produk',
    single_item_pricing_stock: 'Harga & Stok Item Tunggal',
    total_stock: 'Jumlah Stok',
    normal_price: 'Harga Biasa ($)',
    agent_price: 'Harga Ejen ($)',
    promo_price: 'Harga Promosi ($)',
    per_box_pricing_optional: 'Harga Per Kotak (Pilihan)',
    items_per_box: 'Item Per Kotak',
    box_price: 'Harga Kotak ($)',
    box_agent_price: 'Harga Ejen Kotak ($)',
    box_promo_price: 'Harga Promosi Kotak ($)',
    bundle_set_pricing_optional: 'Harga Set Berkumpulan (Pilihan)',
    items_per_bundle: 'Item Per Set',
    bundle_price: 'Harga Set ($)',
    bundle_agent_price: 'Harga Ejen Set ($)',
    bundle_promo_price: 'Harga Promosi Set ($)',
    visual_assets: 'Aset Visual',
    click_to_upload_images: 'Klik untuk memuat naik imej',
    png_jpg_up_to_10mb: 'PNG, JPG sehingga 10MB',
    youtube_video_link_optional: 'Pautan Video Youtube (pilihan)',
    open_youtube: 'Buka YouTube',
    how_to_add_video: 'Cara Menambah Video',
    youtube_guide_step1: 'Klik "Buka YouTube" untuk melawat youtube.com',
    youtube_guide_step2: 'Cari dan buka video yang ingin anda paparkan',
    youtube_guide_step3: 'Salin URL dari bar alamat pelayar',
    youtube_guide_step4: 'Tampal pautan yang disalin ke dalam kotak input ini',
    listing_status: 'Status Penyenaraian',
    confirm_upload: 'Sahkan Muat Naik',
    uploading: 'Memuat naik...',
    please_select_category: 'Sila pilih kategori.',
    please_provide_product_name: 'Sila berikan nama produk.',
    please_upload_image: 'Sila muat naik sekurang-kurangnya satu imej.',
    product_uploaded_successfully: 'Produk berjaya dimuat naik!',
    failed_to_upload_product: 'Gagal memuat naik produk. Sila cuba lagi.',
    upload_single_item_page: 'Muat Naik Item Tunggal',
    available_products: 'Produk Tersedia',
    all: 'Semua',
    live: 'Langsung',
    hold: 'Tahan',
    deactive: 'Nyahaktif',
    low_stock: 'Stok Rendah',
    out_of_stock: 'Kehabisan Stok',
    quick_action_subtitle: 'Anda tidak perlu meninggalkan halaman ini untuk membuat kemas kini ringkas. Untuk mengedit item dengan cepat:',
    double_click: 'Dwi-klik',
    directly_on_the: 'secara langsung pada sel',
    stock_price_status: 'Stok, Harga atau Status',
    cells_in_inventory: 'dalam jadual inventori di bawah.',
    hit: 'Tekan',
    enter: 'Enter',
    or_click_green_save: 'atau klik ikon Simpan hijau untuk menggunakan perubahan anda dengan serta-merta!',
    got_it_thanks: 'Faham, Terima kasih!',
    prep_step2_pt1: 'Isi semua lajur yang diperlukan (ditandakan dengan asterisk',
    for_the: 'Untuk',
    image_filename: 'Image_Filename',
    column_input: 'lajur, masukkan nama fail tepat imej anda (cth.,',
    firework_png: 'firework-01.png',
    note_on_folders: 'Nota tentang Folder:',
    do_not_place_images: 'Sistem kami menggunakan enjin imbasan pintar. Nama folder tidak penting. Kami mencari semua direktori dalam arkib ZIP anda secara automatik untuk memadankan nama fail dengan sempurna.',
    right_click_select: 'Klik kanan folder dan pilih',
    compress_to_zip: 'Mampat ke fail ZIP',
    click: 'Klik',
    confirm_import: 'Sahkan Import',
    to_permanently_save: 'untuk menyimpan produk secara kekal ke pangkalan data.',
    review_validation: 'Semak sebarang ralat pengesahan yang diserlahkan dalam warna merah.',

    upload_single_item: 'Muat Naik Item Tunggal',
    bulk_upload: 'Muat Naik Pukal',
    download_template: 'Muat Turun Templat',
    bulk_upload_guidance: 'Panduan Muat Naik Pukal',
    go_to_bulk_upload: 'Pergi ke Muat Naik Pukal',
    source_file: 'Fail Sumber',
    please_select_file: 'Sila pilih satu fail...',
    browse: 'Semak imbas...',
    download_quick_import_template: 'Muat turun fail import pantas',
    upload_btn: 'Muat Naik',
    invalid_zip_err: 'Sila muat naik fail .zip yang sah mengandungi templat Excel dan imej.',
    available_on_store: 'Tersedia di kedai',
    awaiting_action: 'Menunggu tindakan',
    unpublished_items: 'Item tidak diterbitkan',
    low_stock: 'Stok Rendah',
    below_10_items: 'Bawah 10 item',
    out_of_stock: 'Kehabisan Stok',
    items_left: 'item tinggal',
    best_least_selling: 'Produk Paling Laris & Kurang Laris',
    see_which_products: 'Lihat produk mana yang paling banyak dan paling kurang dijual bulan ini',
    no_sales_data: 'Tiada data jualan untuk bulan ini',
    product_stock_overview: 'Gambaran Keseluruhan Stok Produk',
    monitor_products: 'Pantau produk mana yang tersedia, semakin berkurangan atau habis dijual',
    inventory_list: 'Senarai Inventori',
    permanent_deletion: 'Pemadaman Kekal',
    quick_action_guide: 'Panduan Tindakan Pantas',
    inline_editing_shortcuts: 'Pintasan Penyuntingan Sebaris',
    quick_action_step1: 'Dwi-klik terus pada sel Stok, Harga atau Status dalam jadual inventori di bawah.',
    quick_action_step2: 'Taipkan nilai baharu anda atau pilih status baharu daripada juntai bawah.',
    quick_action_step3: 'Tekan Enter atau klik ikon Simpan hijau untuk menggunakan perubahan anda dengan serta-merta!',
    bulk_guide_intro: 'Selamat datang ke panduan Muat Naik Pukal. Sistem import pukal kami membolehkan anda memuat naik beratus-ratus produk dan imej yang sepadan dengan mudah secara serentak menggunakan satu arkib ZIP. Ikuti garis panduan profesional ini untuk memastikan pengalaman import data yang sempurna.',
    prep_excel_template: 'Sediakan Templat Excel',
    prep_step1: 'Mulakan dengan memuat turun templat rasmi daripada halaman Produk.',
    prep_step2: 'Isi semua lajur yang diperlukan (ditandakan dengan asterisk *)',
    prep_step3: 'Untuk lajur Image_Filename, masukkan nama fail tepat imej anda (cth., firework-01.png)',
    prep_step4: 'Pastikan ejaan dan sambungan fail (.png, .jpg) sepadan dengan fail imej sebenar anda dengan sempurna.',
    pack_zip_archive: 'Pek Arkib ZIP',
    pack_step1: 'Satukan templat anda yang telah diisi dan semua imej produk ke dalam satu folder.',
    pack_step2: 'Nota tentang Folder: Jangan letakkan imej di dalam subfolder. Simpan semuanya dalam folder akar.',
    pack_step3: 'Buat folder baharu pada komputer anda.',
    pack_step4: 'Pindahkan templat yang telah siap dan semua fail imej berkaitan ke dalam folder ini.',
    pack_step5: 'Klik kanan folder dan pilih Mampat ke fail ZIP (Windows) atau Mampat (Mac).',
    upload_verify: 'Muat Naik dan Sahkan',
    upload_step1: 'Pergi ke halaman Muat Naik Pukal dan lepaskan pakej ZIP yang baru anda buat.',
    upload_step2: 'Sistem akan mengekstrak dan menganalisis pakej ZIP anda secara tempatan.',
    upload_step3: 'Jadual pratonton akan muncul yang menunjukkan dengan tepat rupa produk anda.',
    upload_step4: 'Semak sebarang ralat pengesahan yang diserlahkan dalam warna merah. Hanya baris yang sempurna akan disimpan.',
    upload_step5: 'Klik Sahkan Import untuk menyimpan produk secara kekal ke pangkalan data.',

    admin_title: 'Admin',
    super_admin: 'Super Admin',
    yes_logout: 'Ya, Log keluar',
    delete_category_title: 'Padam Kategori?',
    delete_category_q: 'Adakah anda pasti mahu memadam',
    delete_category_warn: '? Tindakan ini tidak boleh dibatalkan. Semua produk di bawah kategori ini akan kehilangan kaitan kategori mereka.',
    delete_category_btn: 'Padam Kategori',
    total_categories: 'Jumlah Kategori',
    organized_folders: 'Folder tersusun',
    across_all_categories: 'Merentasi semua kategori',
    on_hold_category: 'Kategori Ditahan',
    hidden_from_frontend: 'Tersembunyi dari bahagian hadapan',
    category_id: 'ID Kategori',
    category_name: 'Nama Kategori',
    product_id: 'ID Produk',
    product_name: 'Nama Produk',
    all: 'Semua',
    live: 'Langsung',
    hold: 'Tahan',
    create_new_category: 'Cipta Kategori Baru',
    create_category_desc: 'Tambah kategori produk baru untuk menyusun inventori anda dan membantu pelanggan mencari produk dengan mudah.',
    category_created: 'Kategori Dicipta!',
    category_info: 'Maklumat Kategori',
    category_code_url: 'Kod Kategori (Kunci URL)',
    category_code_desc: 'Kod unik untuk URL kategori (tiada ruang, gunakan - atau _)',
    chinese_translation_optional: 'Terjemahan Cina (pilihan)',
    display_order_optional: 'Susunan Paparan (pilihan)',
    lower_numbers_first: 'Nombor yang lebih rendah muncul dahulu',
    category_desc_optional: 'Penerangan Kategori (pilihan)',
    hide_category_desc: 'Sembunyikan kategori ini dan semua produknya dari bahagian hadapan.',
    category_photo: 'Foto Kategori',
    category_photo_desc: 'Muat naik foto yang mewakili kategori ini',
    drag_drop_image: 'Seret & lepaskan imej anda di sini',
    or_click_browse: 'atau klik untuk menyemak imbas',
    image_restrictions: 'PNG, JPG, JPEG sehingga 10MB',
    image_preview: 'Pratonton Imej',
    image_preview_desc: 'Pratonton imej akan muncul di sini',
    tips: 'Petua',
    clear_image_tip: 'Gunakan imej jelas yang paling mewakili kategori tersebut.',
    save_category: 'Simpan Kategori',
    edit_category: 'Edit Kategori',
    edit_category_desc: 'Ubah butiran kategori atau kemas kini aset visualnya.',
    category_updated: 'Kategori Dikemas Kini!',
    update_category: 'Kemas Kini Kategori',
    confirm_delete: 'Sahkan Padam',
    delete_category_warn_2: 'Selepas pemadaman, semua produk di bawah kategori ini akan disembunyikan',
    saving: 'Menyimpan...',
    add_new_product: 'Tambah Produk Baharu',
    delete_selected: 'Padam Terpilih',
    got_it: 'Faham',
    per_order: 'Setiap Pesanan',
    total_items: 'Jumlah Item',
    by_revenue_this_period: 'Berdasarkan hasil tempoh ini',
    units_sold_count: 'unit terjual',
    order_information: 'Maklumat Pesanan',
    total_orders_this_week: 'Jumlah Pesanan Minggu Ini',
    recent_transactions: 'Transaksi Terkini',
    view_more: 'Lihat Lagi',
    cash_on_delivery: 'Tunai Semasa Penghantaran',
    duitnow_bank_transfer: 'Pindahan Bank DuitNow',
    self_collect: 'Ambil Sendiri',
    delivery: 'Penghantaran',
    delivering: 'Menghantar',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // 1. Instantly retrieve saved preference from memory on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('admin_selected_language');
      if (savedLang && ['en', 'zh', 'ms'].includes(savedLang)) {
        setLanguageState(savedLang as Language);
      }
    }
  }, []);

  // 2. Custom setLanguage wrapper to update state & persist to localStorage and DB
  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('admin_selected_language', lang);
      try {
        await fetch('/api/admin/profile', {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ language: lang })
        });
      } catch (err) {
        console.error('Failed to save language preference to DB', err);
      }
    }
  };

  // 3. Keep database preferences in sync if logged in as admin
  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const res = await fetch('/api/admin/profile');
        if (res.ok) {
          const data = await res.json();
          if (data.language) {
            setLanguage(data.language as Language);
          }
        }
      } catch (err) {}
    };
    fetchSettings();
  }, []);

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
